package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.SearchView;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/** A search menu to be able to search any recipe in the app */
public class SearchActivity extends AppCompatActivity {

    /** List of recipes */
    private ListView list;
    private List<String> items = Arrays.asList("Brown Rice",
            "Barley Rice",
            "Pea Rice",
            "Black Bean Rice",
            "Red Bean Rice",
            "Ogokbap",
            "Chestnut Rice",
            "Nutrition Stone Pot Rice",
            "Sweet Potato Rice",
            "Kimchi Rice",
            "Sliced Rice",
            "Bean Sprout Rice",
            "Oyster Rice",
            "Chicken Hotbed",
            "Bibimbap",
            "Janggukbap",
            "Rice Roll",
            "White Porridge",
            "Mung Bean Porridge",
            "Bean Porridge",
            "Red Bean Porridge",
            "Pine Nut Porridge",
            "Jujube Porridge",
            "Grilled Porridge",
            "Zucchini Porridge",
            "Pumpkin Porridge",
            "Chicken Porridge",
            "Janggukjuk",
            "Oyster Porridge",
            "Abalone Porridge",
            "Black Sesame Porridge",
            "Tarak Porridge",
            "Noodles Soup",
            "Chicken Noodle",
            "Fish Tray",
            "Seafood Noodle",
            "Bibim Noodles",
            "Spicy Buckwheat Noodles",
            "Cold Raw Fish Noodles",
            "Cold Noodles With Cold Buckwheat Noodles",
            "Pine Nut Noodles",
            "Cold Bean Noodles",
            "Dumpling Soup",
            "Dumpling Noodles",
            "Gyua Statue",
            "Sublime Dumpling",
            "Fish Dumpling",
            "Pork Tteokguk",
            "Rice-Cake Soup",
            "Sujebi",
            "Ae Stew",
            "Seaweed Soup",
            "Sea Mustard Soup",
            "Dried Pollack Soup",
            "Fish Roe Soup",
            "Clam Soup",
            "Chochi Soup",
            "Radish Paste Soup",
            "Bean Sprout Soup",
            "Toran Stew",
            "Opening Soup",
            "Hot Spicy Meat Stew",
            "Cod Soup",
            "Naengi Soup",
            "Cabbage Soup",
            "Spinach Soup",
            "Aukguk",
            "Short Rib Soup",
            "Beef-Bone Soup",
            "Tails Soup",
            "Samgyetang",
            "Seolleongtang",
            "Yongbongtang",
            "Heat Chicken Stew",
            "Chueotang",
            "Imja Water Soup",
            "Cold Chicken Stew",
            "Cold Cucumber Soup",
            "Umu Cold Soup",
            "Soy Bean Paste Stew",
            "Wild Chive Soy Bean Paste Stew",
            "Bean Paste Stew",
            "Raw Beef Stew",
            "Cheonggukjang Stew",
            "Ecological Stew",
            "Soft Tofu Stew",
            "Oyster Tofu Stew",
            "Salted Pollack Roe Stew",
            "Salted Zucchini Soup Stew",
            "Kimchi Stew",
            "Soybean Soup",
            "Beef Stew",
            "Mushroom Stew",
            "Sea Bream Noodles",
            "Seafood Stew",
            "Octopus Stew",
            "Tofu Stew",
            "Fresh Furnace",
            "Steamed Pork Ribs",
            "Steamed Situation",
            "Braised Beef Ribs",
            "Steamed Chicken",
            "Steamed Large Fish",
            "Squid Sundae",
            "Steamed Monkfish",
            "Fishing Sone",
            "Pumpkin Sone",
            "Cucumber",
            "Branched",
            "Tofu Sone",
            "Eggplant Greens",
            "Gujeolpan",
            "Bracken Greens",
            "Canine Leaf Vegetables",
            "Cold Greens",
            "Balloon Flower",
            "Water Parsley",
            "Radish Greens",
            "Knee Greens",
            "Mewi Greens",
            "Pogo Mushroom Vegetables",
            "Mungbean Sprouts",
            "Spinach Greens",
            "Dried Radish Leaves",
            "Zucchini Greens",
            "Chwinamul",
            "Bean Sprouts",
            "Japchae",
            "Bamboo Shoots",
            "Tangpyeongchae",
            "Salted Salad",
            "Deodeok Saengchae",
            "Spicy Spring Salted Vegetables",
            "Raw Radish Salad",
            "Raw Cucumbers",
            "Chamul Raw Salted Salad",
            "Seasoned Seaweed",
            "Mustard Vegetables",
            "Seasoned Acorns",
            "Seasoned Buckwheat Cake",
            "Braised Beef",
            "Braised Hairtail Radish",
            "Braised Radish Mackerel",
            "Braised Fish",
            "Braised Early",
            "Braised Potatoes",
            "Braised Lotus Root",
            "Braised Beans",
            "Braised Tofu",
            "Abalone Plant",
            "Mussel Grass",
            "Jeyuk Bokkeum",
            "Stir-Fried Chicken Ribs",
            "Stir-Fried Octopus",
            "Royal Stir-Fried Rice Cake",
            "Neoviani",
            "Grilled Short Rib Patties",
            "Grilled Beef Ribs",
            "Bulgogi",
            "Grilled Spicy Pork",
            "Grilled Chicken",
            "Grilled Oysters",
            "Grilled Mackerel",
            "Grilled Dried Pollack",
            "Grilled Hairtail",
            "Grilled Early Seasoning",
            "Guljeon",
            "Pancake Shrimp Pancake",
            "Seafood Pajeon",
            "Potato Pancake",
            "Sesame Leaf Pancake",
            "Red Pepper Pancake",
            "Zucchini Pancake",
            "Before Lotus Root",
            "Mushroom Pancake",
            "Bindaetteok",
            "Jangtteok",
            "Sub-San-Jeok",
            "Songi-San-Jeok",
            "Korean Style Raw Beef",
            "Raw Skate",
            "Raw Octopus",
            "Raw Dureup",
            "Green Onion Bundles",
            "Water Parsley And Beef Ties",
            "Boiled Beef Shank Slices",
            "Pyeonyuk",
            "Jokpyeon",
            "Beef Jerky",
            "Kim Bu-Gak",
            "Knot Rice Bowl",
            "Pickled Red Pepper",
            "Pickled Sesame Leaves",
            "Pickled Garlic",
            "Pickled Garlic Pickles",
            "Pickled Radish",
            "Cucumber And Beef",
            "Salted Oysters With Hot Pepper",
            "Soy Sauce Marinated Crab",
            "Salted Squid",
            "Flatfish Sikhae",
            "Cabbage Kimchi",
            "Bossam Kimchi",
            "White Kimchi",
            "Cubed Radish Kimchi",
            "Chonggak Kimchi",
            "Nabak Kimchi",
            "Dongchimi",
            "Pomegranate Kimchi",
            "Fresh Kimchi",
            "Long Kimchi",
            "Godeulgi Kimchi",
            "Young Radish Kimchi",
            "Cucumber Gourd",
            "Green Onion Kimchi",
            "Thick Rice Cake",
            "Snow White",
            "Rainbow Rice Cake",
            "Songpyeon",
            "Cinnamon Rice Cake",
            "Yak-Bap",
            "Pumpkin Rice Cake",
            "Patsirutteok",
            "Injeolmi",
            "Pounded Rice Cake",
            "Juak",
            "Chalsujubukkumi",
            "Hwajeon",
            "Gyeongdan",
            "Danja",
            "Yakgwa",
            "Maejakgwa",
            "Gangjeong",
            "Tea Confectionery",
            "Balloon Flower Garden And",
            "Lotus Root Pavilion",
            "Ginger Eggs",
            "Yulan",
            "Bamcho",
            "Jujube Grass",
            "Omija Jelly",
            "Plum Tea",
            "Ginseng Tea",
            "Ginger Tea",
            "Boiled Pear",
            "Persimmon Punch",
            "Sikhye",
            "Omija Fruit Salad",
            "Citron Fruit Salad",
            "Onesobyung",
            "Potato Chili Paste Stew",
            "Beef Pyeony Salad",
            "Chives Pancake",
            "Grilled Beef Brisket",
            "Acorn Pancake",
            "Stir-Fried Octopus And Thin Noodles",
            "Perilla Soup",
            "Braised Anchovies And White Beans",
            "Braised Dried Anchovies",
            "Braised Raw Peanuts",
            "Braised Burdock Pork Roll",
            "Braised Konjac",
            "Braised Potato Fish Cake",
            "Braised Radish Kodari",
            "Steamed Perilla Leaves",
            "Andong Steamed Chicken",
            "Dried Pollack Stick Rice Gangjeong",
            "Tofu Fried Cake",
            "Stir-Fried Garlic Dried Shrimp",
            "Stir-Fried Small Anchovy Nuts",
            "Stir-Fried Burdock Salad",
            "Stir-Fried Anchovy And Chili Paste",
            "Stir-Fried Seaweed Stem",
            "Stir-Fried Squid Salad",
            "Dry Green Algae Dish",
            "Squid And Pork Belly Bulgogi",
            "Grilled Eggplant Seasoning",
            "Grilled Tofu Seasoning",
            "Grilled Braised Spice With Spicy Sauce",
            "Grilled Kodari Seasoning",
            "Leaf Greens",
            "Dried Eggplant Greens",
            "Seasoned With Water Blue",
            "Seasoned Raw Oysters",
            "Seasoned Skate",
            "Seasoned Sea Snails",
            "Seasoned With Garlic Bell Pepper Paste",
            "Seasoned With Green Pepper Paste",
            "Seasoned Chicken Breasts With Pine Nut Sauce",
            "Pickled Soy Radish",
            "Pickled Mushrooms",
            "Pickled Green Pepper Soy Sauce",
            "Pickled Pollack",
            "Pickled Cucumbers",
            "Pickled Bean Leaves With Soybean Paste",
            "Pickled Kimchi",
            "Pickled Onions",
            "Cucumber Pickles",
            "Cabbage Pickles",
            "Paprika Pickles",
            "Seasoned Cabbage",
            "Chives Kimchi",
            "Green Pepper Kimchi",
            "Cucumber Kimchi",
            "Fruit Water Kimchi",
            "Instant Water Kimchi",
            "Cheongpo Mukjeon",
            "Corn Pancake",
            "Green Bean Pancake",
            "Bingtteok",
            "Mussel Seaweed Soup",
            "Clear Soup With Cod",
            "Burdock Perilla Soup",
            "Soybean Paste Soup With Vegetables",
            "Thick Soybean Paste Soup",
            "Soybean Paste Soup With Ramie Clam",
            "Spicy Seafood Soup",
            "Bulgogi Stew",
            "Fish Cake Stew",
            "Seaweed Cucumber Cold Soup",
            "Five Grain Rice",
            "Grilled Radish Rice",
            "Rice With Seasoned Thistle",
            "Seaweed Abalone Porridge",
            "Fruit Salad",
            "Lotus Root Salad",
            "Bulgogi Cold Salad",
            "Jellyfish Cold Salad",
            "Tricolored Egg Roll",
            "Steamed Earthenware Egg",
            "Seasoned Green Onion Salad With Meat",
            "Seaweed Vinegar Sashimi",
            "Sweet Rice Pancake",
            "Ginger Dry Fruit",
            "Walnut Crackers",
            "Salted Greens",
            "Soybean Sauce",
            "Stir-Fried Laver",
            "Seasoned With Chubby Balloon Flower",
            "Bulgogi Webfoot Octopus Stew",
            "Cold Salad With Seafood",
            "Seasoned Fish And Pork",
            "Stir-Fried Spinach Shrimp",
            "Steamed Back Ribs",
            "Red Pepper Kimchi",
            "Salted Sea Squirt",
            "Braised Saury",
            "Thermal Movie Beam Surface",
            "Seasoned Seasoned Seasoned Seasoned Seasoned With Vegetables",
            "Seasoned With Dried Pollack",
            "Braised Quarigo Chives",
            "Seafood Egg Soup",
            "Steamed Tofu Shrimp",
            "Steamed Spicy Ribs",
            "Seasoned Cucumbers",
            "Chicken Stew",
            "Fresh Fish Soup",
            "Buckwheat Noodles",
            "Braised Nuts",
            "Pickled Deodeok",
            "Rice With Tuna Sashimi",
            "Braised Kelp",
            "Pollack Egg Roll",
            "Grilled Samchigo Chili Sauce",
            "Stir-Fried Eggplant",
            "Braised Squid Soy Sauce",
            "Braised Mackerel Kimchi",
            "Seaweed Soup With New Egg Mussels",
            "Green Laver Pancake",
            "Seasoned Green Laver",
            "Oyster Soup",
            "Samchi Cracker",
            "Beef Vegetable Roll",
            "Pork Back-Bone Stew",
            "Grilled Pork Belly",
            "Seafood Soybean Paste Pot",
            "Sweet Potato Sweet Pumpkin Salad",
            "Steamed Kodari",
            "Windproof Vegetable Seasoning",
            "Chamulmuul Radish",
            "Korean Melon Kkakdugi",
            "Cold Buckwheat Buckwheat Noodles",
            "Seasoned Coriander",
            "Strong Tofu Red Pepper Paste",
            "Burdock Pickles",
            "Chwinamul Soy Bean Paste Soup",
            "Seasoned Cheongpo Muk",
            "Braised Sweet Pumpkin",
            "Assorted Ssambap",
            "Burdock Japchae",
            "Mushroom Soft Tofu Perilla Soup",
            "Mushroom Mustard Cold Salad",
            "Sesame Leaf Stir-Fry",
            "Stir-Fried Onions",
            "Enoki Mushroom Vegetable Pancake",
            "Ham Tofu Pancake",
            "Lettuce Fresh Kimchi",
            "Seasoned Seaweed With Vinegar",
            "Braised Radish",
            "Stir-Fried Dried Shrimp",
            "Broccoli Tofu Salad",
            "Braised Bungeoppo",
            "Stir-Fried Squid Soy Sauce",
            "Seasoned Wild Vegetables",
            "Seasoned Salad",
            "Seasoned Onion Cucumbers",
            "Stir-Fried Perilla Sprouts",
            "Braised Clams",
            "Seasoned Cockles",
            "Stir-Fried Red Pepper Paste With Dried Pollack",
            "Braised Burdock",
            "Oyster Kimchi Soup And Rice",
            "Salted Pollack Roe Tofu Stew",
            "Dongtae Spicy Soup",
            "Wheat Wrap",
            "Braised Octopus Stew",
            "Sea Cucumber Nurungji Soup",
            "Seafood Salad",
            "Grilled Oyster Skewers",
            "Oyster Salad",
            "Seasoned With Soothing",
            "Seasoned Skate Sashimi",
            "Grilled Burdock Beef",
            "Manila Clam Kalguksu",
            "Seasoned Webfoot Octopus Sashimi",
            "Grilled Clam Butter",
            "Spicy Rockfish Soup",
            "The Durbbakan Wrap",
            "Stir-Fried Bamboo Shoots",
            "Seasoned Blue Crabs",
            "Fried Yellow Croake",
            "Grilled Webfoot Octopus Seasoning",
            "Chwinamul Doenjang Salad",
            "Blue Crab Stew",
            "Steamed Sea Squirt Bean Sprouts",
            "Squid Spicy Soup",
            "Chives Semi Kimchi",
            "Stir-Fried Squid",
            "Mungge Bibimbap",
            "Abalone Vinegar Sashimi",
            "Young Radish Greens",
            "Eel Nutrition Rice",
            "Strong Doenjang Yeol Movie Bibimbap",
            "Yeolmu Kimchi Bibim Noodle",
            "Eel Chives Soup",
            "Toran Soup",
            "Octopus Yeonpo Soup",
            "Toenmi Soy Bean Paste Soup",
            "Shiitake Beef Brisket Doenjang Stew",
            "Mussel Clear Soup",
            "Seasoned With Julienne",
            "Fried Shrimp",
            "Sweet And Sour Mushrooms",
            "Grilled Shrimp Skewers",
            "Grilled Gizzard",
            "Raw Onion Octopus",
            "Steamed Sweet Pumpkin",
            "Steamed Kimchi With Seasoned Mackerel",
            "Radish Bean Sprout Soup",
            "Beef Bulgogi",
            "Kimchi Fried Rice",
            "Spam Mayo Rice With Rice",
            "Yeolmu Bibimbap",
            "A Rice Topped With Tonkatsu",
            "Kkomak Bibimbap",
            "Spicy Sausage Stew",
            "Pork Kimchi Stew",
            "Beef Radish Soup",
            "Squid Radish Soup",
            "Mussel Fish Cake Soup",
            "Squid Spicy Seafood Noodles",
            "Noodles For The Feast",
            "Bibimdangmyeon",
            "Stir-Fried Seafood Udon",
            "Stir-Fried Beef Rice Noodles",
            "Seafood Pasta",
            "Mille-Feuille-Nabe",
            "Back Rib Barbecue",
            "Steamed Pork Belly Kimchi Roll",
            "Pan-Fried Pork Belly Host Food",
            "Sweet And Sour Pork",
            "Smoked Salmon",
            "Squid Minari Ganghoe",
            "Seasoned Duck",
            "Seaweed Oyster Soup",
            "Grilled Abalone Butter",
            "Grilled Eel",
            "Sweet Pumpkin Porridge",
            "Salmon Steak",
            "Black Bean Noodles Tteokbokki",
            "Sweet Potato Mattang",
            "Beef Rice Balls",
            "Cramey Fried Tofu Rice Balls",
            "Seasoned Chives And Cucumbers",
            "Kimjaban",
            "Grilled Tofu Salad",
            "Green Algae Guljeon",
            "Seasoned Buckwheat Muk Kimchi",
            "Frozen Pollack Pancake",
            "Grilled Mackerel Soy Sauce",
            "Grilled Eel Yangyeom",
            "Seasoned Octopus Candle",
            "Chicken Breast Mustard Salad",
            "Stir-Fried Pork With Soy Sauce",
            "Stir Fried Beef Bok Chung Oyster",
            "Braised Beef Wan",
            "Braised Quarigo Chili Eggs",
            "Braised King Oyster Mushroom",
            "Braised Dried Mussels",
            "Bang-A-Po-Y",
            "Splashing Kelp",
            "Seasoned Dried Pollack",
            "A Fish-Shaped Bun",
            "A Plum Crop",
            "Abalone Dolsotbap",
            "Abalone Earthen Pot",
            "Abalone Kimchi",
            "Acorn Jelly",
            "Acorn Jelly Salad",
            "Agwi-Tang",
            "Ah Wook Guk",
            "Albap",
            "Bacon Rice Cake Skewers",
            "Baekseolg",
            "Bamboo Barrel Rice",
            "Banquet Noodles",
            "Bar Rice Cake",
            "Barley Tea",
            "Bean Leaf Kimchi",
            "Bean Meat",
            "Bean Paste Cabbage Soup",
            "Bean Rice",
            "Bean Soup",
            "Bean Sprout Hangover Soup",
            "Bean Sprout Konjac Bibimmyeon",
            "Bean Sprout Mushroom Stew",
            "Bean-Soup Noodles",
            "Beef Cabbage Soup",
            "Beef Pancake",
            "Bibimguks",
            "Bijibap",
            "Black Rice",
            "Black Sesame Skin",
            "Black-Bean-Sauce Noodles",
            "Black-Bean-Sauce Rice",
            "Blue Crab Soup",
            "Boiled Pork",
            "Boiled Rice Porridge",
            "Bom-Dong Odejeoljeol",
            "Bomalguk",
            "Bone Soup",
            "Bossam",
            "Braised Abalone",
            "Braised Back Rib Kimchi",
            "Braised Beef Brisket",
            "Braised Chestnut",
            "Braised Cutlassfish",
            "Braised Egg",
            "Braised Garlic Almonds",
            "Braised Mackerel And Kimchi",
            "Braised Mackerel",
            "Braised Old Kimchi",
            "Braised Peanuts",
            "Braised Pollack",
            "Braised Pork Garlic",
            "Braised Pork Neck",
            "Braised Quail Eggs",
            "Braised Red Pepper",
            "Braised Short Ribs",
            "Braised Skate",
            "Braised Soybeans",
            "Braised Spicy Chicken",
            "Braised Tuna Potatoes",
            "Broccoli Tuna Warfare",
            "Buckwheat Rice",
            "Buckwheat Warrior",
            "Buldak Stir-Fried Noodles",
            "Bulgogi With Rice",
            "Bulnakjeongol",
            "Bungnamul",
            "Burdock Kimchi",
            "Cabbage Tuna Over Rice",
            "Carrot Rice",
            "Carrot Seasoned With Grilled Radish",
            "Charcoal Spicy Stir-Fried Chicken",
            "Cheese Back Ribs",
            "Cheonggukjang Jjigae",
            "Cheonggukjang",
            "Chicken Curry Rice",
            "Chicken Kebabs",
            "Chicken Soup",
            "Chinese Cabbage Leaf",
            "Chinese Cabbage Soup",
            "Chives Bacon Mallet",
            "Chives Japchae",
            "Chodang Tofu",
            "Chungmu Gimbap",
            "Chupotang",
            "Citron Tea",
            "Clam Kalguksu",
            "Cloud Rice Cake",
            "Cockle-Minarimuchim",
            "Cold Bean Sprout Salad",
            "Cold Buckwheat Noodles",
            "Cold Jellyfish Salad",
            "Cold Noodles With Pollack",
            "Cold Raw Fish Soup",
            "Cold Soup",
            "Cold Soybean Paste Soup",
            "Corn Rice",
            "Corn Tea",
            "Crispy Rice Crust",
            "Crucible Bath",
            "Cucumber Pickle",
            "Cucumber Salad",
            "Cup Rice",
            "Deep-Fried Chicken In Hot Pepper Sauce",
            "Deep-Fried Sweet Pumpkin",
            "Deodeok Jangaji",
            "Deodeok Kimchi",
            "Dongpa Yuk",
            "Dongtaejeon",
            "Doraji Saengchae",
            "Dorajigwa",
            "Dorajimuchim",
            "Doribangbangi",
            "Dried Persimmon Walnut Wraps",
            "Dried Pollack Hangover Soup",
            "Dried Pollack Salad",
            "Dried Pollack",
            "Dried Radish Greens",
            "Dried Radish Kimchi",
            "Dried Radish Salad",
            "Dried Radish",
            "Dried Soybean Paste Seasoned With Dried Radish Leaves",
            "Dulchigi",
            "Dumpling Hot Pot",
            "Dumpling",
            "Egg Dumpling",
            "Egg Rice",
            "Egg Soup",
            "Eggplant Rice",
            "Eggplant Sprouts",
            "Eggplant Tangsu",
            "Eojuk",
            "Eolchutang",
            "Fish Cake Kimchi Jeongol",
            "Fish Cake Pancake",
            "Fish Cake Soup",
            "Five-Spiced Pork",
            "Flat Dumpling",
            "Fried Cheese Potato",
            "Fried Chicken",
            "Fried Eggplant",
            "Fried Onion",
            "Fried Oysters",
            "Fried Rice",
            "Fried Squid",
            "Fried Sweet Potatoes",
            "Fried Tofu Sushi",
            "Fried Vegetables",
            "Fried Walnut Garlic",
            "Galchi Pumpkin Soup",
            "Galnaktang",
            "Gamjazugoroke",
            "Garlic Pickle",
            "Gazamijorim",
            "Ge Gukji",
            "Gijangbap",
            "Ginger Process",
            "Ginseng Process",
            "Glutinous Rice",
            "Godeulpaegi Kimchi",
            "Golbaengi Fire Noodle Salad",
            "Gondre Rice",
            "Gondrenamul",
            "Green Pepper Salad",
            "Grilled Deodeok",
            "Grilled Herring",
            "Grilled Perilla Leaf Tofu",
            "Grilled Pork Ginger",
            "Grilled Pork Ribs",
            "Grilled Rice Cake",
            "Grilled Saesongi Mushroom Soy Sauce",
            "Grilled Saesongi",
            "Grilled Short Ribs",
            "Grilled Shrimp",
            "Grilled Tofu",
            "Grilled Tripe Soy Sauce",
            "Grilled Tripe",
            "Gu Gi-Cha",
            "Guamegi Raw Fish Salad",
            "Gulguk",
            "Hangover Soup",
            "Honey Bread",
            "Honey Butter Sweet Potato",
            "Honey Rice Cake",
            "Hot Pepper Paste Tuna Fried Rice",
            "Hwe Guksu",
            "Japchae Rice",
            "Jjambbong",
            "Jjangdung Fish Soup",
            "Jjimdak",
            "Jjolmyeon",
            "Joebap",
            "Joggi-Guk",
            "Jorangi Tteokguk",
            "Jujube Tea",
            "Kalguksu",
            "Kim Moo-Chim",
            "Kimchi Pancake",
            "Kimchi Soup",
            "Kimchi Sujebi",
            "Kkakdugi",
            "Knee Cartilage Soup",
            "Ko Ji-Guk",
            "Kongbiji",
            "Kongtang",
            "Korean Style Meatball",
            "La Galbi Jjim",
            "Leek Kimchi",
            "Leek Pancake",
            "Lettuce Leaf Salad",
            "Liquor Soup",
            "Lotus Leaf Rice",
            "Lotus Root Stewing",
            "Mak Noodle",
            "Marsh Snail Soup",
            "Mixed Grain Rice",
            "Mixed Kimchi",
            "Mugwort Rice Cake",
            "Mukbap",
            "Mukguk",
            "Mung Bean Rice",
            "Mung Bean Samgyetang",
            "Mushroom Hot Pot",
            "Mushroom Jangjorim",
            "Mushroom Perilla Soup",
            "Mussel Herb",
            "Mussel Soup",
            "Naejangtang",
            "Nakjigui",
            "Neubiani",
            "Nose-Backed Noodles",
            "Nurungji Chicken Soup",
            "Nurungjitang",
            "Oat Rice",
            "Octopus Lotus Pot Stew",
            "Odengguk",
            "Oiseon",
            "Oisobak",
            "Omelet Rice",
            "Omija Hwachae",
            "Onion Egg Rice",
            "Onion Kimchi",
            "Onion Pickle",
            "Owing Japchae",
            "Ox Head Gukbap",
            "Oyster Rice Soup",
            "Oyster Stew",
            "Palbochae",
            "Paprika Beef Horse",
            "Paprika Tuna Warfare",
            "Patbings",
            "Pearl Bibimbap",
            "Perilla Leaf Jeon",
            "Perilla Leaf Kimchi",
            "Perilla Leaf Pickle",
            "Perilla Taro Soup",
            "Pheasant Soup",
            "Pibab",
            "Pickled Garlic Leaves",
            "Pickled Onion",
            "Pollack Soup",
            "Pollack Tofu Stew",
            "Pork And Hot Pepper Paste Stew",
            "Pork And Rice Soup",
            "Pork Belly Gangjeong",
            "Pork Cutlet",
            "Potato Ongshimi",
            "Potato Rice",
            "Potato Songpyeon",
            "Powder Made Of Mixed Grains",
            "Puffed Rice",
            "Pumpkin Beombeok",
            "Pumpkin Pancake",
            "Pumpkin Soup",
            "Pyeongyang Hot Pot",
            "Quince Tea",
            "Radish Ssammari",
            "Rajoy",
            "Ramen Rice",
            "Raw Beef Mixed With Rice",
            "Red Bean Jelly",
            "Red Bean Noodle Soup",
            "Red Pepper Paste Pork Belly",
            "Red Pepper Paste Stew",
            "Rice Ball",
            "Rice Burger",
            "Rice Cake Dumpling Soup",
            "Rice Topped With Eggs",
            "Rice Topped With Octopus",
            "Rice Tteokbokki",
            "Rice With Enoki Mushroom",
            "Rice With Grilled Pancake",
            "Rice With Squid",
            "Roast Duck",
            "Roasted Abalone",
            "Rolled Omelet",
            "Royal Tteokbokki",
            "Sagolguk",
            "Salmon Soy Sauce Braised",
            "Salted Oysters",
            "Samhap",
            "Sanchae Bibimbap",
            "Sancho Pickled Vegetables",
            "Sausage Soy Sauce Braised",
            "Sea Snails Salad",
            "Sea Urchin Seaweed Soup",
            "Seafood Nurungji Soup",
            "Seasoned Bean Sprouts",
            "Seasoned Bracken",
            "Seasoned Cockle",
            "Seasoned Crab Radish",
            "Seasoned Cucumber",
            "Seasoned Duck-Buchu",
            "Seasoned Leek",
            "Seasoned Oyster",
            "Seasoned Perilla Leaves",
            "Seasoned Radish",
            "Seasoned Spicy Chicken",
            "Seasoned Spinach",
            "Seaweed Bibimbap",
            "Seaweed Cold Soup",
            "Seonji Haejangguk",
            "Seonjitguk",
            "Separate Rice Soup",
            "Shark's Dome Exhaust",
            "Shellfish Soup",
            "Shiitake Pancake",
            "Shin Sun Ro",
            "Shirutteok",
            "Shrimp Soft Tofu Egg Soup",
            "Shrimp Soup",
            "Shrimp Sweet Noodles Rice With Rice",
            "Small Walnut-Flavored Cake",
            "Sorghum Rice",
            "Soy Sauce Pork Bulgogi",
            "Spiced Squid",
            "Spicy Blue Crab Sauce Marinated Spicy Sauce",
            "Spicy Braised Short Ribs",
            "Spicy Chicken Soup With Rice",
            "Spicy Cold Noodles",
            "Spicy Fish Stew",
            "Spicy Grilled Chicken",
            "Spicy Stir-Fried Chicken With Cheese",
            "Spinned Bean Paste Soup",
            "Spring Roll",
            "Sprout Bibimbap",
            "Squid Bulgogi",
            "Squid Duruchigi",
            "Squid Kimchi",
            "Ssambap",
            "Ssanghwa-Cha",
            "Steamed Buns",
            "Steamed Dried Corvina",
            "Steamed Eggs",
            "Steamed Sausage Bean Sprouts",
            "Steamed Sea Squirt Bibimbap",
            "Steamed Snow Crab",
            "Steamed Soybean Paste Perilla Leaves",
            "Steamed Stingray",
            "Stew Made With Frozen Pollack",
            "Stir-Fried Anchovies",
            "Stir-Fried Bean Sprouts And Eggs",
            "Stir-Fried Beef Cheonggyeongchae",
            "Stir-Fried Beef Cucumber",
            "Stir-Fried Chicken Breast Mushroom",
            "Stir-Fried Chicken Breast Perilla Leaves",
            "Stir-Fried Chicken Feet",
            "Stir-Fried Cucumber",
            "Stir-Fried Garlic Species",
            "Stir-Fried Pork Belly",
            "Stir-Fried Potatoes",
            "Stir-Fried Pumpkin Tuna",
            "Stir-Fried Rice Cake",
            "Stir-Fried Shrimp Cheonggyeongchae",
            "Stir-Fried Shrimp",
            "Stir-Fried Soondae",
            "Stir-Fried Spam Potato",
            "Stir-Fried Spicy Stir-Fried Chili Pepper Ham",
            "Stir-Fried Tripe",
            "Stir-Fried Udon",
            "Stir-Fried Zucchini Shrimp",
            "Sundae Soup",
            "Sweet And Sour Chicken",
            "Sweet Potato Pancake",
            "Sweet Potato Soup",
            "Sweet Pumpkin Nutrition Rice",
            "Sweet Pumpkin Sikhye",
            "Tadpole Noodles",
            "Tofu And Soybean Paste",
            "Tofu Chagle",
            "Tofu Gangjeong",
            "Tofu Kimchi Egg Soup",
            "Tofu Kimchi",
            "Tofu Pancake",
            "Tofu Rice",
            "Tofu Spam Kimchi Hot Pot",
            "Tofu Spinach Salad",
            "Tray Jjajang",
            "Tray Membrane Noodles",
            "Triangular Rolled-Rice Gimbap",
            "Ttukbaegi Bulgogi",
            "Tuna Bibimbap",
            "Tuna Kimchi Porridge",
            "Turnip Kimchi",
            "Udon",
            "Vegetable Porridge",
            "Wanjatang",
            "Water Parsley Kimchi",
            "Webfoot Octopus Lotus Pot Soup",
            "Webfoot Octopus Salad",
            "Wheat Noodles",
            "White Rice",
            "Yakbap",
            "Yeolmu Kimchi",
            "Yeon Geun Jeon",
            "Yeonpo-Tang",
            "Young Green Pepper Pancake",
            "Yugwa",
            "Yulmu Bap",
            "Yushan Seul",
            "Zelkova Duruchigi",
            "Zucchini Egg Porridge"
            );

    /** Gain user input */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_search);

        Intent intent = getIntent();

        SearchView searchView = findViewById(R.id.search_view);
        TextView resultTextView = findViewById(R.id.textView3);
        resultTextView.setText(getResult());

        searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextSubmit(String query) {
                return false;
            }

            @Override
            public boolean onQueryTextChange(String newText) {
                resultTextView.setText(search(newText));
                return true;
            }
        });
    }

    /** Search function with case being not sensitive*/
    private String search(String query) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < items.size(); i++) {
            String item = items.get(i);
            if (item.toLowerCase().contains(query.toLowerCase())) {
                sb.append(item);
                if (i != items.size() - 1) {
                    sb.append("\n");
                }
            }
        }
        return sb.toString();
    }

    /** Return results of search */
    private String getResult() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < items.size(); i++) {
            String item = items.get(i);
            sb.append(item);
            if (i != items.size() - 1) {
                sb.append("\n");
            }
        }
        return sb.toString();
    }
}