package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.BaseAdapter;
import android.widget.GridView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

/** Side dish recipe list with photos */
public class SecondaryActivity_sidedish extends AppCompatActivity {

    GridView gv_sidedish;

    String[] sidedish_names = {"Gyua Statue",
            "Sublime Dumpling",
            "Fish Dumpling",
            "Fishing Sone",
            "Pumpkin Sone",
            "Cucumber",
            "Branched",
            "Tofu Sone",
            "Eggplant Greens",
            "Gujeolpan",
            "Bracken Greens",
            "Canine Leaf Vegetables",
            "Cold Greens",
            "Balloon Flower",
            "Water Parsley",
            "Radish Greens",
            "Knee Greens",
            "Mewi Greens",
            "Pogo Mushroom Vegetables",
            "Mungbean Sprouts",
            "Spinach Greens",
            "Dried Radish Leaves",
            "Zucchini Greens",
            "Chwinamul",
            "Bean Sprouts",
            "Japchae",
            "Bamboo Shoots",
            "Tangpyeongchae",
            "Salted Salad",
            "Deodeok Saengchae",
            "Spicy Spring Salted Vegetables",
            "Raw Radish Salad",
            "Raw Cucumbers",
            "Chamul Raw Salted Salad",
            "Seasoned Seaweed",
            "Mustard Vegetables",
            "Seasoned Acorns",
            "Seasoned Buckwheat Cake",
            "Braised Beef",
            "Braised Hairtail Radish",
            "Braised Radish Mackerel",
            "Braised Fish",
            "Braised Early",
            "Braised Potatoes",
            "Braised Lotus Root",
            "Braised Beans",
            "Braised Tofu",
            "Abalone Plant",
            "Mussel Grass",
            "Royal Stir-Fried Rice Cake",
            "Kim Bu-Gak",
            "Knot Rice Bowl",
            "Pickled Red Pepper",
            "Pickled Sesame Leaves",
            "Pickled Garlic",
            "Pickled Garlic Pickles",
            "Pickled Radish",
            "Cucumber And Beef",
            "Salted Oysters With Hot Pepper",
            "Soy Sauce Marinated Crab",
            "Salted Squid",
            "Flatfish Sikhae",
            "Cabbage Kimchi",
            "Bossam Kimchi",
            "White Kimchi",
            "Cubed Radish Kimchi",
            "Chonggak Kimchi",
            "Nabak Kimchi",
            "Dongchimi",
            "Pomegranate Kimchi",
            "Fresh Kimchi",
            "Long Kimchi",
            "Godeulgi Kimchi",
            "Young Radish Kimchi",
            "Cucumber Gourd",
            "Green Onion Kimchi",
            "Beef Pyeony Salad",
            "Acorn Pancake",
            "Braised Anchovies And White Beans",
            "Braised Dried Anchovies",
            "Braised Raw Peanuts",
            "Braised Burdock Pork Roll",
            "Braised Konjac",
            "Braised Potato Fish Cake",
            "Braised Radish Kodari",
            "Steamed Perilla Leaves",
            "Dried Pollack Stick Rice Gangjeong",
            "Tofu Fried Cake",
            "Stir-Fried Garlic Dried Shrimp",
            "Stir-Fried Small Anchovy Nuts",
            "Stir-Fried Burdock Salad",
            "Stir-Fried Anchovy And Chili Paste",
            "Stir-Fried Seaweed Stem",
            "Stir-Fried Squid Salad",
            "Dry Green Algae Dish",
            "Leaf Greens",
            "Dried Eggplant Greens",
            "Seasoned With Water Blue",
            "Seasoned Raw Oysters",
            "Seasoned Skate",
            "Seasoned Sea Snails",
            "Seasoned With Garlic Bell Pepper Paste",
            "Seasoned With Green Pepper Paste",
            "Seasoned Chicken Breasts With Pine Nut Sauce",
            "Pickled Soy Radish",
            "Pickled Mushrooms",
            "Pickled Green Pepper Soy Sauce",
            "Pickled Pollack",
            "Pickled Cucumbers",
            "Pickled Bean Leaves With Soybean Paste",
            "Pickled Kimchi",
            "Pickled Onions",
            "Cucumber Pickles",
            "Cabbage Pickles",
            "Paprika Pickles",
            "Seasoned Cabbage",
            "Chives Kimchi",
            "Green Pepper Kimchi",
            "Cucumber Kimchi",
            "Fruit Water Kimchi",
            "Instant Water Kimchi",
            "Fruit Salad",
            "Lotus Root Salad",
            "Bulgogi Cold Salad",
            "Jellyfish Cold Salad",
            "Tricolored Egg Roll",
            "Steamed Earthenware Egg",
            "Seasoned Green Onion Salad With Meat",
            "Seaweed Vinegar Sashimi",
            "Sweet Rice Pancake",
            "Salted Greens",
            "Soybean Sauce",
            "Stir-Fried Laver",
            "Seasoned With Chubby Balloon Flower",
            "Cold Salad With Seafood",
            "Seasoned Fish And Pork",
            "Stir-Fried Spinach Shrimp",
            "Steamed Back Ribs",
            "Red Pepper Kimchi",
            "Salted Sea Squirt",
            "Braised Saury",
            "Seasoned Seasoned Seasoned Seasoned Seasoned With Vegetables",
            "Seasoned With Dried Pollack",
            "Braised Quarigo Chives",
            "Seasoned Cucumbers",
            "Braised Nuts",
            "Pickled Deodeok",
            "Braised Kelp",
            "Pollack Egg Roll",
            "Stir-Fried Eggplant",
            "Braised Squid Soy Sauce",
            "Seasoned Green Laver",
            "Samchi Cracker",
            "Beef Vegetable Roll",
            "Sweet Potato Sweet Pumpkin Salad",
            "Windproof Vegetable Seasoning",
            "Chamulmuul Radish",
            "Korean Melon Kkakdugi",
            "Cold Buckwheat Buckwheat Noodles",
            "Seasoned Coriander",
            "Strong Tofu Red Pepper Paste",
            "Burdock Pickles",
            "Seasoned Cheongpo Muk",
            "Braised Sweet Pumpkin",
            "Burdock Japchae",
            "Mushroom Mustard Cold Salad",
            "Sesame Leaf Stir-Fry",
            "Stir-Fried Onions",
            "Lettuce Fresh Kimchi",
            "Seasoned Seaweed With Vinegar",
            "Braised Radish",
            "Stir-Fried Dried Shrimp",
            "Broccoli Tofu Salad",
            "Braised Bungeoppo",
            "Stir-Fried Squid Soy Sauce",
            "Seasoned Wild Vegetables",
            "Seasoned Salad",
            "Seasoned Onion Cucumbers",
            "Stir-Fried Perilla Sprouts",
            "Braised Clams",
            "Seasoned Cockles",
            "Stir-Fried Red Pepper Paste With Dried Pollack",
            "Braised Burdock",
            "Braised Octopus Stew",
            "Oyster Salad",
            "Seasoned With Soothing",
            "Seasoned Skate Sashimi",
            "The Durbbakan Wrap",
            "Stir-Fried Bamboo Shoots",
            "Seasoned Blue Crabs",
            "Fried Yellow Croake",
            "Chwinamul Doenjang Salad",
            "Chives Semi Kimchi",
            "Stir-Fried Squid",
            "Abalone Vinegar Sashimi",
            "Young Radish Greens",
            "Seasoned With Julienne",
            "Fried Shrimp",
            "Steamed Sweet Pumpkin",
            "Steamed Kimchi With Seasoned Mackerel",
            "Squid Minari Ganghoe",
            "Black Bean Noodles Tteokbokki",
            "Sweet Potato Mattang",
            "Seasoned Chives And Cucumbers",
            "Kimjaban",
            "Grilled Tofu Salad",
            "Seasoned Buckwheat Muk Kimchi",
            "Seasoned Octopus Candle",
            "Chicken Breast Mustard Salad",
            "Braised Beef Wan",
            "Braised Quarigo Chili Eggs",
            "Braised King Oyster Mushroom",
            "Braised Dried Mussels",
            "Splashing Kelp",
            "Seasoned Dried Pollack",
            "Abalone Kimchi",
            "Acorn Jelly",
            "Acorn Jelly Salad",
            "Bean Leaf Kimchi",
            "Bom-Dong Odejeoljeol",
            "Braised Back Rib Kimchi",
            "Braised Chestnut",
            "Braised Egg",
            "Braised Garlic Almonds",
            "Braised Peanuts",
            "Braised Quail Eggs",
            "Braised Red Pepper",
            "Braised Soybeans",
            "Braised Tuna Potatoes",
            "Bungnamul",
            "Burdock Kimchi",
            "Carrot Seasoned With Grilled Radish",
            "Chinese Cabbage Leaf",
            "Chives Bacon Mallet",
            "Chives Japchae",
            "Chodang Tofu",
            "Cockle-Minarimuchim",
            "Cold Bean Sprout Salad",
            "Cold Jellyfish Salad",
            "Cucumber Pickle",
            "Cucumber Salad",
            "Deep-Fried Sweet Pumpkin",
            "Deodeok Jangaji",
            "Deodeok Kimchi",
            "Doraji Saengchae",
            "Dorajimuchim",
            "Dried Pollack Salad",
            "Dried Pollack",
            "Dried Radish Greens",
            "Dried Radish Kimchi",
            "Dried Radish Salad",
            "Dried Radish",
            "Dried Soybean Paste Seasoned With Dried Radish Leaves",
            "Dumpling",
            "Egg Dumpling",
            "Eggplant Sprouts",
            "Eggplant Tangsu",
            "Flat Dumpling",
            "Fried Cheese Potato",
            "Fried Eggplant",
            "Fried Onion",
            "Fried Oysters",
            "Fried Squid",
            "Fried Sweet Potatoes",
            "Fried Vegetables",
            "Fried Walnut Garlic",
            "Garlic Pickle",
            "Godeulpaegi Kimchi",
            "Golbaengi Fire Noodle Salad",
            "Gondrenamul",
            "Green Pepper Salad",
            "Grilled Saesongi",
            "Guamegi Raw Fish Salad",
            "Kim Moo-Chim",
            "Kkakdugi",
            "Korean Style Meatball",
            "Leek Kimchi",
            "Lettuce Leaf Salad",
            "Mixed Kimchi",
            "Mushroom Jangjorim",
            "Mussel Herb",
            "Oiseon",
            "Oisobak",
            "Omija Hwachae",
            "Onion Kimchi",
            "Onion Pickle",
            "Owing Japchae",
            "Paprika Beef Horse",
            "Perilla Leaf Kimchi",
            "Perilla Leaf Pickle",
            "Pickled Garlic Leaves",
            "Pickled Onion",
            "Pork Belly Gangjeong",
            "Potato Ongshimi",
            "Pumpkin Beombeok",
            "Radish Ssammari",
            "Rolled Omelet",
            "Salted Oysters",
            "Sancho Pickled Vegetables",
            "Sausage Soy Sauce Braised",
            "Sea Snails Salad",
            "Seasoned Bean Sprouts",
            "Seasoned Bracken",
            "Seasoned Cockle",
            "Seasoned Crab Radish",
            "Seasoned Cucumber",
            "Seasoned Duck-Buchu",
            "Seasoned Leek",
            "Seasoned Oyster",
            "Seasoned Perilla Leaves",
            "Seasoned Radish",
            "Seasoned Spinach",
            "Spiced Squid",
            "Spicy Blue Crab Sauce Marinated Spicy Sauce",
            "Squid Kimchi",
            "Steamed Eggs",
            "Steamed Sausage Bean Sprouts",
            "Steamed Soybean Paste Perilla Leaves",
            "Stir-Fried Anchovies",
            "Stir-Fried Bean Sprouts And Eggs",
            "Stir-Fried Beef Cheonggyeongchae",
            "Stir-Fried Beef Cucumber",
            "Stir-Fried Chicken Breast Mushroom",
            "Stir-Fried Chicken Breast Perilla Leaves",
            "Stir-Fried Cucumber",
            "Stir-Fried Garlic Species",
            "Stir-Fried Potatoes",
            "Stir-Fried Pumpkin Tuna",
            "Stir-Fried Shrimp Cheonggyeongchae",
            "Stir-Fried Shrimp",
            "Stir-Fried Spam Potato",
            "Stir-Fried Spicy Stir-Fried Chili Pepper Ham",
            "Stir-Fried Zucchini Shrimp",
            "Tofu And Soybean Paste",
            "Tofu Gangjeong",
            "Tofu Kimchi",
            "Tofu Spinach Salad",
            "Turnip Kimchi",
            "Water Parsley Kimchi",
            "Webfoot Octopus Salad",
            "Yeolmu Kimchi",
            "Yeon Geun Jeon"


    };
    int[] sidedish_images = {
            R.drawable.gyua_statue,
            R.drawable.sublime_dumpling,
            R.drawable.fish_dumpling,
            R.drawable.fishing_sone,
            R.drawable.pumpkin_sone,
            R.drawable.cucumber,
            R.drawable.branched,
            R.drawable.tofu_sone,
            R.drawable.eggplant_greens,
            R.drawable.gujeolpan,
            R.drawable.bracken_greens,
            R.drawable.canine_leaf_vegetables,
            R.drawable.cold_greens,
            R.drawable.balloon_flower,
            R.drawable.water_parsley,
            R.drawable.radish_greens,
            R.drawable.knee_greens,
            R.drawable.mewi_greens,
            R.drawable.pogo_mushroom_vegetables,
            R.drawable.mungbean_sprouts,
            R.drawable.spinach_greens,
            R.drawable.dried_radish_leaves,
            R.drawable.zucchini_greens,
            R.drawable.chwinamul,
            R.drawable.bean_sprouts,
            R.drawable.japchae,
            R.drawable.bamboo_shoots,
            R.drawable.tangpyeongchae,
            R.drawable.salted_salad,
            R.drawable.deodeok_saengchae,
            R.drawable.spicy_spring_salted_vegetables,
            R.drawable.raw_radish_salad,
            R.drawable.raw_cucumbers,
            R.drawable.chamul_raw_salted_salad,
            R.drawable.seasoned_seaweed,
            R.drawable.mustard_vegetables,
            R.drawable.seasoned_acorns,
            R.drawable.seasoned_buckwheat_cake,
            R.drawable.braised_beef,
            R.drawable.braised_hairtail_radish,
            R.drawable.braised_radish_mackerel,
            R.drawable.braised_fish,
            R.drawable.braised_early,
            R.drawable.braised_potatoes,
            R.drawable.braised_lotus_root,
            R.drawable.braised_beans,
            R.drawable.braised_tofu,
            R.drawable.abalone_plant,
            R.drawable.mussel_grass,
            R.drawable.royal_stir_fried_rice_cake,
            R.drawable.kim_bu_gak,
            R.drawable.knot_rice_bowl,
            R.drawable.pickled_red_pepper,
            R.drawable.pickled_sesame_leaves,
            R.drawable.pickled_garlic,
            R.drawable.pickled_garlic_pickles,
            R.drawable.pickled_radish,
            R.drawable.cucumber_and_beef,
            R.drawable.salted_oysters_with_hot_pepper,
            R.drawable.soy_sauce_marinated_crab,
            R.drawable.salted_squid,
            R.drawable.flatfish_sikhae,
            R.drawable.cabbage_kimchi,
            R.drawable.bossam_kimchi,
            R.drawable.white_kimchi,
            R.drawable.cubed_radish_kimchi,
            R.drawable.chonggak_kimchi,
            R.drawable.nabak_kimchi,
            R.drawable.dongchimi,
            R.drawable.pomegranate_kimchi,
            R.drawable.fresh_kimchi,
            R.drawable.long_kimchi,
            R.drawable.godeulgi_kimchi,
            R.drawable.young_radish_kimchi,
            R.drawable.cucumber_gourd,
            R.drawable.green_onion_kimchi,
            R.drawable.beef_pyeony_salad,
            R.drawable.acorn_pancake,
            R.drawable.braised_anchovies_and_white_beans,
            R.drawable.braised_dried_anchovies,
            R.drawable.braised_raw_peanuts,
            R.drawable.braised_burdock_pork_roll,
            R.drawable.braised_konjac,
            R.drawable.braised_potato_fish_cake,
            R.drawable.braised_radish_kodari,
            R.drawable.steamed_perilla_leaves,
            R.drawable.dried_pollack_stick_rice_gangjeong,
            R.drawable.tofu_fried_cake,
            R.drawable.stir_fried_garlic_dried_shrimp,
            R.drawable.stir_fried_small_anchovy_nuts,
            R.drawable.stir_fried_burdock_salad,
            R.drawable.stir_fried_anchovy_and_chili_paste,
            R.drawable.stir_fried_seaweed_stem,
            R.drawable.stir_fried_squid_salad,
            R.drawable.dry_green_algae_dish,
            R.drawable.leaf_greens,
            R.drawable.dried_eggplant_greens,
            R.drawable.seasoned_with_water_blue,
            R.drawable.seasoned_raw_oysters,
            R.drawable.seasoned_skate,
            R.drawable.seasoned_sea_snails,
            R.drawable.seasoned_with_garlic_bell_pepper_paste,
            R.drawable.seasoned_with_green_pepper_paste,
            R.drawable.seasoned_chicken_breasts_with_pine_nut_sauce,
            R.drawable.pickled_soy_radish,
            R.drawable.pickled_mushrooms,
            R.drawable.pickled_green_pepper_soy_sauce,
            R.drawable.pickled_pollack,
            R.drawable.pickled_cucumbers,
            R.drawable.pickled_bean_leaves_with_soybean_paste,
            R.drawable.pickled_onions,
            R.drawable.cucumber_pickles,
            R.drawable.cabbage_pickles,
            R.drawable.paprika_pickles,
            R.drawable.seasoned_cabbage,
            R.drawable.chives_kimchi,
            R.drawable.green_pepper_kimchi,
            R.drawable.cucumber_kimchi,
            R.drawable.fruit_water_kimchi,
            R.drawable.instant_water_kimchi,
            R.drawable.fruit_salad,
            R.drawable.lotus_root_salad,
            R.drawable.bulgogi_cold_salad,
            R.drawable.jellyfish_cold_salad,
            R.drawable.tricolored_egg_roll,
            R.drawable.steamed_earthenware_egg,
            R.drawable.seasoned_green_onion_salad_with_meat,
            R.drawable.seaweed_vinegar_sashimi,
            R.drawable.sweet_rice_pancake,
            R.drawable.salted_greens,
            R.drawable.soybean_sauce,
            R.drawable.stir_fried_laver,
            R.drawable.seasoned_with_chubby_balloon_flower,
            R.drawable.cold_salad_with_seafood,
            R.drawable.seasoned_fish_and_pork,
            R.drawable.stir_fried_spinach_shrimp,
            R.drawable.steamed_back_ribs,
            R.drawable.red_pepper_kimchi,
            R.drawable.salted_sea_squirt,
            R.drawable.braised_saury,
            R.drawable.seasoned_seasoned_seasoned_seasoned_seasoned_with_vegetables,
            R.drawable.seasoned_with_dried_pollack,
            R.drawable.braised_quarigo_chives,
            R.drawable.seasoned_cucumbers,
            R.drawable.braised_nuts,
            R.drawable.pickled_deodeok,
            R.drawable.braised_kelp,
            R.drawable.pollack_egg_roll,
            R.drawable.stir_fried_eggplant,
            R.drawable.braised_squid_soy_sauce,
            R.drawable.seasoned_green_laver,
            R.drawable.samchi_cracker,
            R.drawable.beef_vegetable_roll,
            R.drawable.sweet_potato_sweet_pumpkin_salad,
            R.drawable.windproof_vegetable_seasoning,
            R.drawable.chamulmuul_radish,
            R.drawable.korean_melon_kkakdugi,
            R.drawable.cold_buckwheat_buckwheat_noodles,
            R.drawable.seasoned_coriander,
            R.drawable.strong_tofu_red_pepper_paste,
            R.drawable.burdock_pickles,
            R.drawable.seasoned_cheongpo_muk,
            R.drawable.braised_sweet_pumpkin,
            R.drawable.burdock_japchae,
            R.drawable.mushroom_mustard_cold_salad,
            R.drawable.sesame_leaf_stir_fry,
            R.drawable.stir_fried_onions,
            R.drawable.lettuce_fresh_kimchi,
            R.drawable.seasoned_seaweed_with_vinegar,
            R.drawable.braised_radish,
            R.drawable.stir_fried_dried_shrimp,
            R.drawable.broccoli_tofu_salad,
            R.drawable.braised_bungeoppo,
            R.drawable.stir_fried_squid_soy_sauce,
            R.drawable.seasoned_wild_vegetables,
            R.drawable.seasoned_salad,
            R.drawable.seasoned_onion_cucumbers,
            R.drawable.stir_fried_perilla_sprouts,
            R.drawable.braised_clams,
            R.drawable.seasoned_cockles,
            R.drawable.stir_fried_red_pepper_paste_with_dried_pollack,
            R.drawable.braised_burdock,
            R.drawable.braised_octopus_stew,
            R.drawable.oyster_salad,
            R.drawable.seasoned_with_soothing,
            R.drawable.seasoned_skate_sashimi,
            R.drawable.the_durbbakan_wrap,
            R.drawable.stir_fried_bamboo_shoots,
            R.drawable.seasoned_blue_crabs,
            R.drawable.chwinamul_doenjang_salad,
            R.drawable.stir_fried_squid,
            R.drawable.abalone_vinegar_sashimi,
            R.drawable.young_radish_greens,
            R.drawable.seasoned_with_julienne,
            R.drawable.fried_shrimp,
            R.drawable.steamed_sweet_pumpkin,
            R.drawable.steamed_kimchi_with_seasoned_mackerel,
            R.drawable.squid_minari_ganghoe,
            R.drawable.black_bean_noodles_tteokbokki,
            R.drawable.sweet_potato_mattang,
            R.drawable.seasoned_chives_and_cucumbers,
            R.drawable.kimjaban,
            R.drawable.grilled_tofu_salad,
            R.drawable.seasoned_buckwheat_muk_kimchi,
            R.drawable.seasoned_octopus_candle,
            R.drawable.chicken_breast_mustard_salad,
            R.drawable.braised_beef_wan,
            R.drawable.braised_quarigo_chili_eggs,
            R.drawable.braised_king_oyster_mushroom,
            R.drawable.braised_dried_mussels,
            R.drawable.splashing_kelp,
            R.drawable.seasoned_dried_pollack,
            R.drawable.bean_leaf_kimchi,
            R.drawable.bom_dong_odejeoljeol,
            R.drawable.braised_back_rib_kimchi,
            R.drawable.braised_chestnut,
            R.drawable.braised_egg,
            R.drawable.braised_garlic_almonds,
            R.drawable.braised_peanuts,
            R.drawable.braised_quail_eggs,
            R.drawable.braised_soybeans,
            R.drawable.braised_tuna_potatoes,
            R.drawable.bungnamul,
            R.drawable.burdock_kimchi,
            R.drawable.carrot_seasoned_with_grilled_radish,
            R.drawable.chinese_cabbage_leaf,
            R.drawable.chives_bacon_mallet,
            R.drawable.chives_japchae,
            R.drawable.chodang_tofu,
            R.drawable.cockle_minarimuchim,
            R.drawable.cold_bean_sprout_salad,
            R.drawable.cold_jellyfish_salad,
            R.drawable.cucumber_pickle,
            R.drawable.cucumber_salad,
            R.drawable.deep_fried_sweet_pumpkin,
            R.drawable.deodeok_jangaji,
            R.drawable.doraji_saengchae,
            R.drawable.dorajimuchim,
            R.drawable.dried_radish_salad,
            R.drawable.dried_soybean_paste_seasoned_with_dried_radish_leaves,
            R.drawable.dumpling,
            R.drawable.egg_dumpling,
            R.drawable.eggplant_tangsu,
            R.drawable.flat_dumpling,
            R.drawable.fried_cheese_potato,
            R.drawable.fried_eggplant,
            R.drawable.fried_onion,
            R.drawable.fried_oysters,
            R.drawable.fried_squid,
            R.drawable.fried_sweet_potatoes,
            R.drawable.fried_vegetables,
            R.drawable.fried_walnut_garlic,
            R.drawable.garlic_pickle,
            R.drawable.golbaengi_fire_noodle_salad,
            R.drawable.green_pepper_salad,
            R.drawable.guamegi_raw_fish_salad,
            R.drawable.kim_moo_chim,
            R.drawable.korean_style_meatball,
            R.drawable.lettuce_leaf_salad,
            R.drawable.mixed_kimchi,
            R.drawable.mussel_herb,
            R.drawable.oiseon,
            R.drawable.oisobak,
            R.drawable.omija_hwachae,
            R.drawable.onion_pickle,
            R.drawable.owing_japchae,
            R.drawable.paprika_beef_horse,
            R.drawable.perilla_leaf_pickle,
            R.drawable.pickled_onion,
            R.drawable.pork_belly_gangjeong,
            R.drawable.potato_ongshimi,
            R.drawable.pumpkin_beombeok,
            R.drawable.radish_ssammari,
            R.drawable.rolled_omelet,
            R.drawable.salted_oysters,
            R.drawable.sancho_pickled_vegetables,
            R.drawable.sausage_soy_sauce_braised,
            R.drawable.sea_snails_salad,
            R.drawable.seasoned_bean_sprouts,
            R.drawable.seasoned_bracken,
            R.drawable.seasoned_cockle,
            R.drawable.seasoned_crab_radish,
            R.drawable.seasoned_cucumber,
            R.drawable.seasoned_duck_buchu,
            R.drawable.seasoned_oyster,
            R.drawable.seasoned_radish,
            R.drawable.seasoned_spinach,
            R.drawable.spicy_blue_crab_sauce_marinated_spicy_sauce,
            R.drawable.steamed_eggs,
            R.drawable.steamed_sausage_bean_sprouts,
            R.drawable.steamed_soybean_paste_perilla_leaves,
            R.drawable.stir_fried_anchovies,
            R.drawable.stir_fried_bean_sprouts_and_eggs,
            R.drawable.stir_fried_beef_cheonggyeongchae,
            R.drawable.stir_fried_beef_cucumber,
            R.drawable.stir_fried_chicken_breast_mushroom,
            R.drawable.stir_fried_chicken_breast_perilla_leaves,
            R.drawable.stir_fried_cucumber,
            R.drawable.stir_fried_pumpkin_tuna,
            R.drawable.stir_fried_shrimp_cheonggyeongchae,
            R.drawable.stir_fried_spam_potato,
            R.drawable.stir_fried_spicy_stir_fried_chili_pepper_ham,
            R.drawable.stir_fried_zucchini_shrimp,
            R.drawable.tofu_and_soybean_paste,
            R.drawable.tofu_gangjeong,
            R.drawable.tofu_kimchi,
            R.drawable.tofu_spinach_salad,
            R.drawable.turnip_kimchi,
            R.drawable.water_parsley_kimchi,
            R.drawable.yeolmu_kimchi,
            R.drawable.yeon_geun_jeon
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_secondary_sidedish);

        gv_sidedish = findViewById(R.id.gv_sidedish);

        CustomAdapter customAdapter = new CustomAdapter(sidedish_names, sidedish_images,this);

        gv_sidedish.setAdapter(customAdapter);

        gv_sidedish.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
                String selectedName = sidedish_names[i];
                int selectedImage = sidedish_images[i];

                startActivity(new Intent(SecondaryActivity_sidedish.this, Fooddescription.class).putExtra("name",selectedName).putExtra("image",selectedImage));
            }
        });

    }

    /** Gateway from list of recipes to Fooddescription */
    public class CustomAdapter extends BaseAdapter{
        private String[] imageNames;
        private int[] imagePhotos;
        private Context context;
        private LayoutInflater layoutInflater;

        public CustomAdapter(String[] imageNames, int[] imagePhotos, Context context) {
            this.imageNames = imageNames;
            this.imagePhotos = imagePhotos;
            this.context = context;
            this.layoutInflater = (LayoutInflater) context.getSystemService(LAYOUT_INFLATER_SERVICE);

        }

        @Override
        public int getCount() {
            return imagePhotos.length;
        }

        @Override
        public Object getItem(int position) {
            return null;
        }

        @Override
        public long getItemId(int position) {
            return 0;
        }

        @Override
        public View getView(int i, View view, ViewGroup viewGroup) {
            if(view == null) {
                view = layoutInflater.inflate(R.layout.gv_sidedish_rowitems, viewGroup, false);
            }

            TextView tv_sidedish = view.findViewById(R.id.tv_sidedish);
            ImageView iv_sidedish = view.findViewById(R.id.iv_sidedish);

            tv_sidedish.setText(imageNames[i]);
            iv_sidedish.setImageResource(imagePhotos[i]);

            return view;
        }
    }
}