package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Toast;

/** List of recipes which high protein is the main health benefit gain from the recipe */
public class TertiaryActivity_health_highprotein extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tertiary_health_highprotein);

        String[] highproteinitems = {"Pea Rice",
                "Black Bean Rice",
                "Red Bean Rice",
                "Ogokbap",
                "Oyster Rice",
                "Chicken Hotbed",
                "Janggukbap",
                "Chicken Porridge",
                "Oyster Porridge",
                "Abalone Porridge",
                "Chicken Noodle",
                "Fish Tray",
                "Seafood Noodle",
                "Cold Bean Noodles",
                "Dumpling Soup",
                "Rice-Cake Soup",
                "Dried Pollack Soup",
                "Fish Roe Soup",
                "Clam Soup",
                "Chochi Soup",
                "Hot Spicy Meat Stew",
                "Cod Soup",
                "Short Rib Soup",
                "Beef-Bone Soup",
                "Tails Soup",
                "Samgyetang",
                "Seolleongtang",
                "Yongbongtang",
                "Heat Chicken Stew",
                "Chueotang",
                "Imja Water Soup",
                "Cold Chicken Stew",
                "Soy Bean Paste Stew",
                "Wild Chive Soy Bean Paste Stew",
                "Bean Paste Stew",
                "Cheonggukjang Stew",
                "Ecological Stew",
                "Soft Tofu Stew",
                "Oyster Tofu Stew",
                "Soybean Soup",
                "Beef Stew",
                "Sea Bream Noodles",
                "Seafood Stew",
                "Octopus Stew",
                "Tofu Stew",
                "Fresh Furnace",
                "Steamed Pork Ribs",
                "Steamed Situation",
                "Braised Beef Ribs",
                "Steamed Chicken",
                "Steamed Large Fish",
                "Squid Sundae",
                "Steamed Monkfish",
                "Fishing Sone",
                "Tofu Sone",
                "Gujeolpan",
                "Japchae",
                "Braised Beef",
                "Braised Hairtail Radish",
                "Braised Radish Mackerel",
                "Braised Fish",
                "Braised Early",
                "Braised Beans",
                "Braised Tofu",
                "Abalone Plant",
                "Mussel Grass",
                "Jeyuk Bokkeum",
                "Stir-Fried Chicken Ribs",
                "Stir-Fried Octopus",
                "Royal Stir-Fried Rice Cake",
                "Neoviani",
                "Grilled Short Rib Patties",
                "Grilled Beef Ribs",
                "Bulgogi",
                "Grilled Spicy Pork",
                "Grilled Chicken",
                "Grilled Oysters",
                "Grilled Mackerel",
                "Grilled Dried Pollack",
                "Grilled Hairtail",
                "Grilled Early Seasoning",
                "Guljeon",
                "Pancake Shrimp Pancake",
                "Seafood Pajeon",
                "Bindaetteok",
                "Sub-San-Jeok",
                "Korean Style Raw Beef",
                "Raw Skate",
                "Raw Octopus",
                "Boiled Beef Shank Slices",
                "Pyeonyuk",
                "Jokpyeon",
                "Beef Jerky",
                "Salted Oysters With Hot Pepper",
                "Soy Sauce Marinated Crab",
                "Salted Squid",
                "Flatfish Sikhae",
                "Beef Pyeony Salad",
                "Grilled Beef Brisket",
                "Stir-Fried Octopus And Thin Noodles",
                "Braised Anchovies And White Beans",
                "Braised Dried Anchovies",
                "Braised Raw Peanuts",
                "Braised Burdock Pork Roll",
                "Braised Potato Fish Cake",
                "Braised Radish Kodari",
                "Andong Steamed Chicken",
                "Dried Pollack Stick Rice Gangjeong",
                "Tofu Fried Cake",
                "Stir-Fried Small Anchovy Nuts",
                "Stir-Fried Anchovy And Chili Paste",
                "Stir-Fried Squid Salad",
                "Squid And Pork Belly Bulgogi",
                "Grilled Tofu Seasoning",
                "Grilled Braised Spice With Spicy Sauce",
                "Grilled Kodari Seasoning",
                "Seasoned Raw Oysters",
                "Seasoned Skate",
                "Seasoned Sea Snails",
                "Seasoned With Green Pepper Paste",
                "Seasoned Chicken Breasts With Pine Nut Sauce",
                "Pickled Bean Leaves With Soybean Paste",
                "Mussel Seaweed Soup",
                "Clear Soup With Cod",
                "Soybean Paste Soup With Vegetables",
                "Thick Soybean Paste Soup",
                "Soybean Paste Soup With Ramie Clam",
                "Spicy Seafood Soup",
                "Bulgogi Stew",
                "Fish Cake Stew",
                "Grilled Radish Rice",
                "Seaweed Abalone Porridge",
                "Bulgogi Cold Salad",
                "Tricolored Egg Roll",
                "Steamed Earthenware Egg",
                "Seasoned Green Onion Salad With Meat",
                "Soybean Sauce",
                "Bulgogi Webfoot Octopus Stew",
                "Cold Salad With Seafood",
                "Seasoned Fish And Pork",
                "Stir-Fried Spinach Shrimp",
                "Steamed Back Ribs",
                "Salted Sea Squirt",
                "Braised Saury",
                "Seasoned Seasoned Seasoned Seasoned Seasoned With Vegetables",
                "Seafood Egg Soup",
                "Steamed Tofu Shrimp",
                "Steamed Spicy Ribs",
                "Chicken Stew",
                "Fresh Fish Soup",
                "Rice With Tuna Sashimi",
                "Pollack Egg Roll",
                "Grilled Samchigo Chili Sauce",
                "Braised Squid Soy Sauce",
                "Braised Mackerel Kimchi",
                "Seaweed Soup With New Egg Mussels",
                "Oyster Soup",
                "Samchi Cracker",
                "Beef Vegetable Roll",
                "Pork Back-Bone Stew",
                "Grilled Pork Belly",
                "Seafood Soybean Paste Pot",
                "Steamed Kodari",
                "Strong Tofu Red Pepper Paste",
                "Chwinamul Soy Bean Paste Soup",
                "Mushroom Soft Tofu Perilla Soup",
                "Ham Tofu Pancake",
                "Stir-Fried Dried Shrimp",
                "Broccoli Tofu Salad",
                "Braised Bungeoppo",
                "Stir-Fried Squid Soy Sauce",
                "Braised Clams",
                "Seasoned Cockles",
                "Stir-Fried Red Pepper Paste With Dried Pollack",
                "Oyster Kimchi Soup And Rice",
                "Salted Pollack Roe Tofu Stew",
                "Dongtae Spicy Soup",
                "Braised Octopus Stew",
                "Sea Cucumber Nurungji Soup",
                "Seafood Salad",
                "Grilled Oyster Skewers",
                "Oyster Salad",
                "Seasoned Skate Sashimi",
                "Grilled Burdock Beef",
                "Manila Clam Kalguksu",
                "Seasoned Webfoot Octopus Sashimi",
                "Grilled Clam Butter",
                "Spicy Rockfish Soup",
                "The Durbbakan Wrap",
                "Seasoned Blue Crabs",
                "Fried Yellow Croake",
                "Grilled Webfoot Octopus Seasoning",
                "Chwinamul Doenjang Salad",
                "Blue Crab Stew",
                "Squid Spicy Soup",
                "Stir-Fried Squid",
                "Mungge Bibimbap",
                "Abalone Vinegar Sashimi",
                "Eel Nutrition Rice",
                "Eel Chives Soup",
                "Octopus Yeonpo Soup",
                "Toenmi Soy Bean Paste Soup",
                "Shiitake Beef Brisket Doenjang Stew",
                "Mussel Clear Soup",
                "Seasoned With Julienne",
                "Fried Shrimp",
                "Grilled Shrimp Skewers",
                "Grilled Gizzard",
                "Raw Onion Octopus",
                "Steamed Kimchi With Seasoned Mackerel",
                "Beef Bulgogi",
                "Spam Mayo Rice With Rice",
                "Kkomak Bibimbap",
                "Pork Kimchi Stew",
                "Beef Radish Soup",
                "Squid Radish Soup",
                "Mussel Fish Cake Soup",
                "Squid Spicy Seafood Noodles",
                "Stir-Fried Beef Rice Noodles",
                "Seafood Pasta",
                "Mille-Feuille-Nabe",
                "Back Rib Barbecue",
                "Steamed Pork Belly Kimchi Roll",
                "Pan-Fried Pork Belly Host Food",
                "Sweet And Sour Pork",
                "Smoked Salmon",
                "Squid Minari Ganghoe",
                "Seasoned Duck",
                "Seaweed Oyster Soup",
                "Grilled Abalone Butter",
                "Grilled Eel",
                "Salmon Steak",
                "Beef Rice Balls",
                "Cramey Fried Tofu Rice Balls",
                "Grilled Tofu Salad",
                "Green Algae Guljeon",
                "Frozen Pollack Pancake",
                "Grilled Mackerel Soy Sauce",
                "Grilled Eel Yangyeom",
                "Seasoned Octopus Candle",
                "Chicken Breast Mustard Salad",
                "Stir-Fried Pork With Soy Sauce",
                "Stir Fried Beef Bok Chung Oyster",
                "Braised Beef Wan",
                "Braised Quarigo Chili Eggs",
                "Braised Dried Mussels",
                "Bang-A-Po-Y",
                "Seasoned Dried Pollack",
                "Abalone Dolsotbap",
                "Abalone Earthen Pot",
                "Abalone Kimchi",
                "Agwi-Tang",
                "Albap",
                "Bacon Rice Cake Skewers",
                "Bean Meat",
                "Bean Paste Cabbage Soup",
                "Bean Rice",
                "Bean Soup",
                "Bean-Soup Noodles",
                "Beef Cabbage Soup",
                "Beef Pancake",
                "Black-Bean-Sauce Noodles",
                "Black-Bean-Sauce Rice",
                "Blue Crab Soup",
                "Boiled Pork",
                "Bone Soup",
                "Bossam",
                "Braised Abalone",
                "Braised Back Rib Kimchi",
                "Braised Beef Brisket",
                "Braised Cutlassfish",
                "Braised Egg",
                "Braised Mackerel And Kimchi",
                "Braised Mackerel",
                "Braised Peanuts",
                "Braised Pollack",
                "Braised Pork Garlic",
                "Braised Pork Neck",
                "Braised Quail Eggs",
                "Braised Short Ribs",
                "Braised Skate",
                "Braised Soybeans",
                "Braised Spicy Chicken",
                "Braised Tuna Potatoes",
                "Broccoli Tuna Warfare",
                "Buldak Stir-Fried Noodles",
                "Bulgogi With Rice",
                "Bulnakjeongol",
                "Cabbage Tuna Over Rice",
                "Charcoal Spicy Stir-Fried Chicken",
                "Cheese Back Ribs",
                "Cheonggukjang Jjigae",
                "Chicken Curry Rice",
                "Chicken Kebabs",
                "Chodang Tofu",
                "Clam Kalguksu",
                "Cockle-Minarimuchim",
                "Cold Noodles With Pollack",
                "Cold Soybean Paste Soup",
                "Crucible Bath",
                "Deep-Fried Chicken In Hot Pepper Sauce",
                "Dongpa Yuk",
                "Dongtaejeon",
                "Doribangbangi",
                "Dried Pollack Hangover Soup",
                "Dried Pollack Salad",
                "Dumpling Hot Pot",
                "Dumpling",
                "Egg Rice",
                "Egg Soup",
                "Eojuk",
                "Eolchutang",
                "Fish Cake Kimchi Jeongol",
                "Fish Cake Pancake",
                "Fish Cake Soup",
                "Fried Cheese Potato",
                "Fried Chicken",
                "Fried Oysters",
                "Fried Squid",
                "Fried Tofu Sushi",
                "Galchi Pumpkin Soup",
                "Gamjazugoroke",
                "Gazamijorim",
                "Golbaengi Fire Noodle Salad",
                "Grilled Herring",
                "Grilled Perilla Leaf Tofu",
                "Grilled Pork Ginger",
                "Grilled Pork Ribs",
                "Grilled Short Ribs",
                "Grilled Shrimp",
                "Grilled Tofu",
                "Grilled Tripe",
                "Guamegi Raw Fish Salad",
                "Gulguk",
                "Hot Pepper Paste Tuna Fried Rice",
                "Hwe Guksu",
                "Jjambbong",
                "Jjimdak",
                "Joggi-Guk",
                "Kongbiji",
                "Kongtang",
                "Korean Style Meatball",
                "La Galbi Jjim",
                "Mung Bean Samgyetang",
                "Mussel Herb",
                "Nakjigui",
                "Neubiani",
                "Nurungji Chicken Soup",
                "Omelet Rice",
                "Ox Head Gukbap",
                "Oyster Rice Soup",
                "Palbochae",
                "Paprika Beef Horse",
                "Pollack Tofu Stew",
                "Pork And Hot Pepper Paste Stew",
                "Pork And Rice Soup",
                "Pork Belly Gangjeong",
                "Pork Cutlet",
                "Red Pepper Paste Pork Belly",
                "Rice Cake Dumpling Soup",
                "Rice Topped With Eggs",
                "Rice Topped With Octopus",
                "Rice With Squid",
                "Roast Duck",
                "Roasted Abalone",
                "Rolled Omelet",
                "Salmon Soy Sauce Braised",
                "Salted Oysters",
                "Samhap",
                "Sausage Soy Sauce Braised",
                "Sea Snails Salad",
                "Seafood Nurungji Soup",
                "Seasoned Cockle",
                "Seasoned Crab Radish",
                "Seasoned Oyster",
                "Seasoned Spicy Chicken",
                "Seonji Haejangguk",
                "Shellfish Soup",
                "Shin Sun Ro",
                "Shrimp Soft Tofu Egg Soup",
                "Shrimp Soup",
                "Soy Sauce Pork Bulgogi",
                "Spiced Squid",
                "Spicy Blue Crab Sauce Marinated Spicy Sauce",
                "Spicy Braised Short Ribs",
                "Spicy Chicken Soup With Rice",
                "Spicy Fish Stew",
                "Spicy Grilled Chicken",
                "Spicy Stir-Fried Chicken With Cheese",
                "Spinned Bean Paste Soup",
                "Squid Bulgogi",
                "Squid Duruchigi",
                "Squid Kimchi",
                "Steamed Dried Corvina",
                "Steamed Eggs",
                "Steamed Sausage Bean Sprouts",
                "Steamed Sea Squirt Bibimbap",
                "Steamed Snow Crab",
                "Steamed Stingray",
                "Stew Made With Frozen Pollack",
                "Stir-Fried Bean Sprouts And Eggs",
                "Stir-Fried Beef Cheonggyeongchae",
                "Stir-Fried Beef Cucumber",
                "Stir-Fried Chicken Breast Mushroom",
                "Stir-Fried Chicken Breast Perilla Leaves",
                "Stir-Fried Chicken Feet",
                "Stir-Fried Pork Belly",
                "Stir-Fried Pumpkin Tuna",
                "Stir-Fried Shrimp Cheonggyeongchae",
                "Stir-Fried Shrimp",
                "Stir-Fried Spam Potato",
                "Stir-Fried Spicy Stir-Fried Chili Pepper Ham",
                "Stir-Fried Tripe",
                "Stir-Fried Udon",
                "Tofu And Soybean Paste",
                "Tofu Chagle",
                "Tofu Gangjeong",
                "Tofu Kimchi Egg Soup",
                "Tofu Kimchi",
                "Tofu Pancake",
                "Tofu Rice",
                "Tofu Spam Kimchi Hot Pot",
                "Tofu Spinach Salad",
                "Tray Jjajang",
                "Tray Membrane Noodles",
                "Triangular Rolled-Rice Gimbap",
                "Ttukbaegi Bulgogi",
                "Tuna Bibimbap",
                "Tuna Kimchi Porridge",
                "Wanjatang",
                "Webfoot Octopus Salad",
                "Yeonpo-Tang",
                "Yushan Seul",
        };
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, highproteinitems);
        ListView listView = (ListView) findViewById(R.id.highproteinlist);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(
                new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int i, long id) {
                        String highproteinitems = String.valueOf(parent.getItemAtPosition(i));
                        Toast.makeText(TertiaryActivity_health_highprotein.this, highproteinitems, Toast.LENGTH_SHORT);
                    }
                }
        );
    }
}