package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Toast;

/** List of recipes which rich in fibre is the main health benefit gain from the recipe */
public class TertiaryActivity_health_richfibre extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tertiary_health_richfibre);

        String[] richfibreitems = {"Brown Rice",
                "Barley Rice",
                "Ogokbap",
                "Chestnut Rice",
                "Nutrition Stone Pot Rice",
                "Sweet Potato Rice",
                "Kimchi Rice",
                "Sliced Rice",
                "Bean Sprout Rice",
                "Bibimbap",
                "Janggukbap",
                "Rice Roll",
                "Jujube Porridge",
                "Grilled Porridge",
                "Zucchini Porridge",
                "Pumpkin Porridge",
                "Bibim Noodles",
                "Spicy Buckwheat Noodles",
                "Dumpling Noodles",
                "Gyua Statue",
                "Sublime Dumpling",
                "Fish Dumpling",
                "Sujebi",
                "Ae Stew",
                "Seaweed Soup",
                "Sea Mustard Soup",
                "Radish Paste Soup",
                "Bean Sprout Soup",
                "Toran Stew",
                "Hot Spicy Meat Stew",
                "Cod Soup",
                "Naengi Soup",
                "Cabbage Soup",
                "Spinach Soup",
                "Aukguk",
                "Chueotang",
                "Imja Water Soup",
                "Cold Cucumber Soup",
                "Umu Cold Soup",
                "Soy Bean Paste Stew",
                "Wild Chive Soy Bean Paste Stew",
                "Bean Paste Stew",
                "Raw Beef Stew",
                "Cheonggukjang Stew",
                "Ecological Stew",
                "Soft Tofu Stew",
                "Oyster Tofu Stew",
                "Salted Pollack Roe Stew",
                "Salted Zucchini Soup Stew",
                "Kimchi Stew",
                "Soybean Soup",
                "Beef Stew",
                "Mushroom Stew",
                "Seafood Stew",
                "Octopus Stew",
                "Tofu Stew",
                "Fresh Furnace",
                "Squid Sundae",
                "Steamed Monkfish",
                "Fishing Sone",
                "Pumpkin Sone",
                "Cucumber",
                "Branched",
                "Eggplant Greens",
                "Gujeolpan",
                "Bracken Greens",
                "Canine Leaf Vegetables",
                "Cold Greens",
                "Balloon Flower",
                "Water Parsley",
                "Radish Greens",
                "Knee Greens",
                "Mewi Greens",
                "Pogo Mushroom Vegetables",
                "Mungbean Sprouts",
                "Spinach Greens",
                "Dried Radish Leaves",
                "Zucchini Greens",
                "Chwinamul",
                "Bean Sprouts",
                "Japchae",
                "Bamboo Shoots",
                "Tangpyeongchae",
                "Salted Salad",
                "Deodeok Saengchae",
                "Spicy Spring Salted Vegetables",
                "Raw Radish Salad",
                "Raw Cucumbers",
                "Chamul Raw Salted Salad",
                "Seasoned Seaweed",
                "Mustard Vegetables",
                "Seasoned Acorns",
                "Seasoned Buckwheat Cake",
                "Braised Hairtail Radish",
                "Braised Radish Mackerel",
                "Braised Potatoes",
                "Braised Lotus Root",
                "Stir-Fried Chicken Ribs",
                "Seafood Pajeon",
                "Potato Pancake",
                "Sesame Leaf Pancake",
                "Red Pepper Pancake",
                "Zucchini Pancake",
                "Before Lotus Root",
                "Mushroom Pancake",
                "Bindaetteok",
                "Jangtteok",
                "Sub-San-Jeok",
                "Songi-San-Jeok",
                "Raw Dureup",
                "Green Onion Bundles",
                "Water Parsley And Beef Ties",
                "Kim Bu-Gak",
                "Knot Rice Bowl",
                "Pickled Red Pepper",
                "Pickled Sesame Leaves",
                "Pickled Garlic",
                "Pickled Garlic Pickles",
                "Pickled Radish",
                "Cucumber And Beef",
                "Cabbage Kimchi",
                "Bossam Kimchi",
                "White Kimchi",
                "Cubed Radish Kimchi",
                "Chonggak Kimchi",
                "Nabak Kimchi",
                "Dongchimi",
                "Pomegranate Kimchi",
                "Fresh Kimchi",
                "Long Kimchi",
                "Godeulgi Kimchi",
                "Young Radish Kimchi",
                "Cucumber Gourd",
                "Green Onion Kimchi",
                "Balloon Flower Garden And",
                "Lotus Root Pavilion",
                "Ginger Eggs",
                "Potato Chili Paste Stew",
                "Beef Pyeony Salad",
                "Chives Pancake",
                "Acorn Pancake",
                "Perilla Soup",
                "Braised Burdock Pork Roll",
                "Braised Konjac",
                "Braised Radish Kodari",
                "Steamed Perilla Leaves",
                "Andong Steamed Chicken",
                "Stir-Fried Garlic Dried Shrimp",
                "Stir-Fried Burdock Salad",
                "Stir-Fried Seaweed Stem",
                "Dry Green Algae Dish",
                "Grilled Eggplant Seasoning",
                "Leaf Greens",
                "Dried Eggplant Greens",
                "Seasoned With Water Blue",
                "Seasoned Sea Snails",
                "Seasoned With Garlic Bell Pepper Paste",
                "Seasoned With Green Pepper Paste",
                "Pickled Soy Radish",
                "Pickled Mushrooms",
                "Pickled Pollack",
                "Pickled Cucumbers",
                "Pickled Bean Leaves With Soybean Paste",
                "Pickled Kimchi",
                "Pickled Onions",
                "Cucumber Pickles",
                "Cabbage Pickles",
                "Paprika Pickles",
                "Seasoned Cabbage",
                "Chives Kimchi",
                "Green Pepper Kimchi",
                "Cucumber Kimchi",
                "Fruit Water Kimchi",
                "Instant Water Kimchi",
                "Mussel Seaweed Soup",
                "Clear Soup With Cod",
                "Burdock Perilla Soup",
                "Soybean Paste Soup With Vegetables",
                "Thick Soybean Paste Soup",
                "Soybean Paste Soup With Ramie Clam",
                "Spicy Seafood Soup",
                "Bulgogi Stew",
                "Fish Cake Stew",
                "Seaweed Cucumber Cold Soup",
                "Five Grain Rice",
                "Grilled Radish Rice",
                "Rice With Seasoned Thistle",
                "Seaweed Abalone Porridge",
                "Fruit Salad",
                "Lotus Root Salad",
                "Bulgogi Cold Salad",
                "Jellyfish Cold Salad",
                "Tricolored Egg Roll",
                "Seasoned Green Onion Salad With Meat",
                "Seaweed Vinegar Sashimi",
                "Salted Greens",
                "Seasoned With Chubby Balloon Flower",
                "Bulgogi Webfoot Octopus Stew",
                "Cold Salad With Seafood",
                "Stir-Fried Spinach Shrimp",
                "Steamed Back Ribs",
                "Red Pepper Kimchi",
                "Braised Saury",
                "Thermal Movie Beam Surface",
                "Braised Quarigo Chives",
                "Seasoned Cucumbers",
                "Chicken Stew",
                "Pickled Deodeok",
                "Rice With Tuna Sashimi",
                "Braised Kelp",
                "Stir-Fried Eggplant",
                "Braised Mackerel Kimchi",
                "Seaweed Soup With New Egg Mussels",
                "Green Laver Pancake",
                "Seasoned Green Laver",
                "Oyster Soup",
                "Beef Vegetable Roll",
                "Pork Back-Bone Stew",
                "Sweet Potato Sweet Pumpkin Salad",
                "Windproof Vegetable Seasoning",
                "Chamulmuul Radish",
                "Korean Melon Kkakdugi",
                "Cold Buckwheat Buckwheat Noodles",
                "Seasoned Coriander",
                "Burdock Pickles",
                "Chwinamul Soy Bean Paste Soup",
                "Braised Sweet Pumpkin",
                "Assorted Ssambap",
                "Burdock Japchae",
                "Mushroom Soft Tofu Perilla Soup",
                "Mushroom Mustard Cold Salad",
                "Sesame Leaf Stir-Fry",
                "Stir-Fried Onions",
                "Enoki Mushroom Vegetable Pancake",
                "Lettuce Fresh Kimchi",
                "Seasoned Seaweed With Vinegar",
                "Braised Radish",
                "Broccoli Tofu Salad",
                "Seasoned Wild Vegetables",
                "Seasoned Salad",
                "Seasoned Onion Cucumbers",
                "Stir-Fried Perilla Sprouts",
                "Braised Burdock",
                "Oyster Kimchi Soup And Rice",
                "Salted Pollack Roe Tofu Stew",
                "Dongtae Spicy Soup",
                "Wheat Wrap",
                "Sea Cucumber Nurungji Soup",
                "Seafood Salad",
                "Grilled Oyster Skewers",
                "Oyster Salad",
                "Seasoned With Soothing",
                "Grilled Burdock Beef",
                "Spicy Rockfish Soup",
                "The Durbbakan Wrap",
                "Stir-Fried Bamboo Shoots",
                "Chwinamul Doenjang Salad",
                "Blue Crab Stew",
                "Steamed Sea Squirt Bean Sprouts",
                "Squid Spicy Soup",
                "Chives Semi Kimchi",
                "Stir-Fried Squid",
                "Mungge Bibimbap",
                "Young Radish Greens",
                "Eel Nutrition Rice",
                "Strong Doenjang Yeol Movie Bibimbap",
                "Yeolmu Kimchi Bibim Noodle",
                "Eel Chives Soup",
                "Toran Soup",
                "Octopus Yeonpo Soup",
                "Toenmi Soy Bean Paste Soup",
                "Shiitake Beef Brisket Doenjang Stew",
                "Mussel Clear Soup",
                "Sweet And Sour Mushrooms",
                "Raw Onion Octopus",
                "Steamed Sweet Pumpkin",
                "Steamed Kimchi With Seasoned Mackerel",
                "Radish Bean Sprout Soup",
                "Beef Bulgogi",
                "Kimchi Fried Rice",
                "Yeolmu Bibimbap",
                "A Rice Topped With Tonkatsu",
                "Kkomak Bibimbap",
                "Spicy Sausage Stew",
                "Pork Kimchi Stew",
                "Beef Radish Soup",
                "Squid Radish Soup",
                "Squid Spicy Seafood Noodles",
                "Noodles For The Feast",
                "Bibimdangmyeon",
                "Stir-Fried Seafood Udon",
                "Stir-Fried Beef Rice Noodles",
                "Mille-Feuille-Nabe",
                "Steamed Pork Belly Kimchi Roll",
                "Pan-Fried Pork Belly Host Food",
                "Sweet And Sour Pork",
                "Squid Minari Ganghoe",
                "Seasoned Duck",
                "Seaweed Oyster Soup",
                "Sweet Pumpkin Porridge",
                "Sweet Potato Mattang",
                "Beef Rice Balls",
                "Seasoned Chives And Cucumbers",
                "Kimjaban",
                "Grilled Tofu Salad",
                "Green Algae Guljeon",
                "Seasoned Buckwheat Muk Kimchi",
                "Chicken Breast Mustard Salad",
                "Stir-Fried Pork With Soy Sauce",
                "Stir Fried Beef Bok Chung Oyster",
                "Braised Beef Wan",
                "Braised Quarigo Chili Eggs",
                "Braised King Oyster Mushroom",
                "Splashing Kelp",
                "Abalone Earthen Pot",
                "Abalone Kimchi",
                "Acorn Jelly Salad",
                "Ah Wook Guk",
                "Albap",
                "Bamboo Barrel Rice",
                "Banquet Noodles",
                "Bean Leaf Kimchi",
                "Bean Paste Cabbage Soup",
                "Bean Sprout Hangover Soup",
                "Bean Sprout Konjac Bibimmyeon",
                "Bean Sprout Mushroom Stew",
                "Beef Cabbage Soup",
                "Bibimguks",
                "Black Rice",
                "Black-Bean-Sauce Noodles",
                "Black-Bean-Sauce Rice",
                "Bossam",
                "Braised Back Rib Kimchi",
                "Braised Garlic Almonds",
                "Braised Mackerel And Kimchi",
                "Braised Old Kimchi",
                "Braised Red Pepper",
                "Braised Short Ribs",
                "Braised Spicy Chicken",
                "Broccoli Tuna Warfare",
                "Bulgogi With Rice",
                "Bulnakjeongol",
                "Bungnamul",
                "Cabbage Tuna Over Rice",
                "Carrot Rice",
                "Cheonggukjang Jjigae",
                "Chicken Curry Rice",
                "Chinese Cabbage Soup",
                "Chives Japchae",
                "Chungmu Gimbap",
                "Clam Kalguksu",
                "Cockle-Minarimuchim",
                "Cold Bean Sprout Salad",
                "Cold Buckwheat Noodles",
                "Cold Jellyfish Salad",
                "Cold Noodles With Pollack",
                "Cold Soybean Paste Soup",
                "Corn Tea",
                "Cucumber Pickle",
                "Cucumber Salad",
                "Deep-Fried Sweet Pumpkin",
                "Deodeok Jangaji",
                "Deodeok Kimchi",
                "Doraji Saengchae",
                "Dorajigwa",
                "Dorajimuchim",
                "Dried Pollack Salad",
                "Dried Radish Greens",
                "Dried Radish Kimchi",
                "Dried Radish Salad",
                "Dried Soybean Paste Seasoned With Dried Radish Leaves",
                "Dumpling Hot Pot",
                "Dumpling",
                "Eggplant Rice",
                "Eggplant Tangsu",
                "Eolchutang",
                "Fish Cake Kimchi Jeongol",
                "Flat Dumpling",
                "Fried Cheese Potato",
                "Fried Eggplant",
                "Fried Onion",
                "Fried Rice",
                "Fried Sweet Potatoes",
                "Fried Vegetables",
                "Galchi Pumpkin Soup",
                "Gamjazugoroke",
                "Garlic Pickle",
                "Ge Gukji",
                "Godeulpaegi Kimchi",
                "Golbaengi Fire Noodle Salad",
                "Gondre Rice",
                "Gondrenamul",
                "Green Pepper Salad",
                "Grilled Deodeok",
                "Grilled Perilla Leaf Tofu",
                "Grilled Saesongi Mushroom Soy Sauce",
                "Hangover Soup",
                "Honey Butter Sweet Potato",
                "Jjambbong",
                "Jjimdak",
                "Kim Moo-Chim",
                "Kimchi Pancake",
                "Kimchi Sujebi",
                "Leek Kimchi",
                "Leek Pancake",
                "Lettuce Leaf Salad",
                "Lotus Leaf Rice",
                "Mugwort Rice Cake",
                "Mushroom Hot Pot",
                "Mushroom Jangjorim",
                "Mushroom Perilla Soup",
                "Oisobak",
                "Onion Kimchi",
                "Ox Head Gukbap",
                "Oyster Rice Soup",
                "Palbochae",
                "Paprika Beef Horse",
                "Perilla Leaf Jeon",
                "Perilla Leaf Kimchi",
                "Perilla Leaf Pickle",
                "Perilla Taro Soup",
                "Pollack Tofu Stew",
                "Pork And Rice Soup",
                "Pumpkin Beombeok",
                "Radish Ssammari",
                "Red Pepper Paste Stew",
                "Rice With Enoki Mushroom",
                "Rice With Squid",
                "Sanchae Bibimbap",
                "Sancho Pickled Vegetables",
                "Sea Snails Salad",
                "Sea Urchin Seaweed Soup",
                "Seasoned Bean Sprouts",
                "Seasoned Bracken",
                "Seasoned Cucumber",
                "Seasoned Duck-Buchu",
                "Seasoned Leek",
                "Seasoned Perilla Leaves",
                "Seasoned Spinach",
                "Seaweed Cold Soup",
                "Seonji Haejangguk",
                "Shiitake Pancake",
                "Shin Sun Ro",
                "Spicy Fish Stew",
                "Spicy Grilled Chicken",
                "Spinned Bean Paste Soup",
                "Spring Roll",
                "Sprout Bibimbap",
                "Squid Kimchi",
                "Ssambap",
                "Steamed Sausage Bean Sprouts",
                "Steamed Sea Squirt Bibimbap",
                "Steamed Soybean Paste Perilla Leaves",
                "Stew Made With Frozen Pollack",
                "Stir-Fried Bean Sprouts And Eggs",
                "Stir-Fried Beef Cheonggyeongchae",
                "Stir-Fried Beef Cucumber",
                "Stir-Fried Chicken Breast Mushroom",
                "Stir-Fried Chicken Breast Perilla Leaves",
                "Stir-Fried Cucumber",
                "Stir-Fried Garlic Species",
                "Stir-Fried Pumpkin Tuna",
                "Stir-Fried Shrimp Cheonggyeongchae",
                "Stir-Fried Zucchini Shrimp",
                "Sundae Soup",
                "Sweet Potato Pancake",
                "Sweet Potato Soup",
                "Sweet Pumpkin Nutrition Rice",
                "Sweet Pumpkin Sikhye",
                "Tofu Kimchi Egg Soup",
                "Tofu Kimchi",
                "Tofu Spam Kimchi Hot Pot",
                "Tofu Spinach Salad",
                "Tray Jjajang",
                "Tray Membrane Noodles",
                "Triangular Rolled-Rice Gimbap",
                "Ttukbaegi Bulgogi",
                "Tuna Bibimbap",
                "Tuna Kimchi Porridge",
                "Turnip Kimchi",
                "Udon",
                "Vegetable Porridge",
                "Wanjatang",
                "Water Parsley Kimchi",
                "Webfoot Octopus Salad",
                "Yakbap",
                "Yeolmu Kimchi",
                "Yeon Geun Jeon",
                "Yeonpo-Tang",
                "Young Green Pepper Pancake",
                "Yushan Seul",
        };
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, richfibreitems);
        ListView listView = (ListView) findViewById(R.id.richfibrelist);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(
                new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int i, long id) {
                        String richfibreitems = String.valueOf(parent.getItemAtPosition(i));
                        Toast.makeText(TertiaryActivity_health_richfibre.this, richfibreitems, Toast.LENGTH_SHORT);
                    }
                }
        );
    }
}