package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Toast;

/** List of recipes which grains are the main ingredients of the recipe */
public class TertiaryActivity_ingredients_grains extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tertiary_ingredients_grains);

        String[] grainsitems = {"Brown Rice",
                "Barley Rice",
                "Pea Rice",
                "Black Bean Rice",
                "Red Bean Rice",
                "Ogokbap",
                "Chestnut Rice",
                "Nutrition Stone Pot Rice",
                "Oyster Rice",
                "Mung Bean Porridge",
                "Bean Porridge",
                "Red Bean Porridge",
                "Pine Nut Porridge",
                "Jujube Porridge",
                "Zucchini Porridge",
                "Pumpkin Porridge",
                "Black Sesame Porridge",
                "Tarak Porridge",
                "Noodles Soup",
                "Chicken Noodle",
                "Seafood Noodle",
                "Bibim Noodles",
                "Spicy Buckwheat Noodles",
                "Cold Raw Fish Noodles",
                "Cold Noodles With Cold Buckwheat Noodles",
                "Pine Nut Noodles",
                "Cold Bean Noodles",
                "Dumpling Soup",
                "Dumpling Noodles",
                "Gyua Statue",
                "Fish Dumpling",
                "Pork Tteokguk",
                "Rice-Cake Soup",
                "Sujebi",
                "Soy Bean Paste Stew",
                "Wild Chive Soy Bean Paste Stew",
                "Bean Paste Stew",
                "Cheonggukjang Stew",
                "Soft Tofu Stew",
                "Oyster Tofu Stew",
                "Soybean Soup",
                "Tofu Stew",
                "Tofu Sone",
                "Japchae",
                "Braised Potatoes",
                "Braised Beans",
                "Braised Tofu",
                "Royal Stir-Fried Rice Cake",
                "Seafood Pajeon",
                "Thick Rice Cake",
                "Snow White",
                "Rainbow Rice Cake",
                "Cinnamon Rice Cake",
                "Yak-Bap",
                "Pumpkin Rice Cake",
                "Patsirutteok",
                "Injeolmi",
                "Pounded Rice Cake",
                "Juak",
                "Chalsujubukkumi",
                "Hwajeon",
                "Gyeongdan",
                "Danja",
                "Yakgwa",
                "Maejakgwa",
                "Gangjeong",
                "Tea Confectionery",
                "Balloon Flower Garden And",
                "Lotus Root Pavilion",
                "Ginger Eggs",
                "Yulan",
                "Omija Jelly",
                "Stir-Fried Octopus And Thin Noodles",
                "Braised Anchovies And White Beans",
                "Braised Raw Peanuts",
                "Tofu Fried Cake",
                "Stir-Fried Small Anchovy Nuts",
                "Grilled Tofu Seasoning",
                "Corn Pancake",
                "Green Bean Pancake",
                "Bingtteok",
                "Soybean Paste Soup With Ramie Clam",
                "Five Grain Rice",
                "Walnut Crackers",
                "Soybean Sauce",
                "Thermal Movie Beam Surface",
                "Buckwheat Noodles",
                "Braised Nuts",
                "Green Laver Pancake",
                "Seafood Soybean Paste Pot",
                "Chwinamul Soy Bean Paste Soup",
                "Burdock Japchae",
                "Mushroom Soft Tofu Perilla Soup",
                "Ham Tofu Pancake",
                "Broccoli Tofu Salad",
                "Salted Pollack Roe Tofu Stew",
                "Wheat Wrap",
                "Manila Clam Kalguksu",
                "Chwinamul Doenjang Salad",
                "Strong Doenjang Yeol Movie Bibimbap",
                "Toenmi Soy Bean Paste Soup",
                "Noodles For The Feast",
                "Bibimdangmyeon",
                "Stir-Fried Seafood Udon",
                "Seafood Pasta",
                "Black Bean Noodles Tteokbokki",
                "Frozen Pollack Pancake",
                "A Fish-Shaped Bun",
                "Acorn Jelly",
                "Acorn Jelly Salad",
                "Baekseolg",
                "Banquet Noodles",
                "Bar Rice Cake",
                "Barley Tea",
                "Bean Meat",
                "Bean Paste Cabbage Soup",
                "Bean Rice",
                "Bean Soup",
                "Bean Sprout Konjac Bibimmyeon",
                "Bean-Soup Noodles",
                "Beef Pancake",
                "Bibimguks",
                "Bijibap",
                "Black Rice",
                "Black Sesame Skin",
                "Black-Bean-Sauce Noodles",
                "Braised Garlic Almonds",
                "Braised Peanuts",
                "Braised Soybeans",
                "Buckwheat Rice",
                "Buckwheat Warrior",
                "Buldak Stir-Fried Noodles",
                "Cheonggukjang Jjigae",
                "Cheonggukjang",
                "Chives Japchae",
                "Chodang Tofu",
                "Clam Kalguksu",
                "Cloud Rice Cake",
                "Cold Buckwheat Noodles",
                "Cold Noodles With Pollack",
                "Cold Soybean Paste Soup",
                "Corn Rice",
                "Corn Tea",
                "Dried Soybean Paste Seasoned With Dried Radish Leaves",
                "Flat Dumpling",
                "Fried Tofu Sushi",
                "Fried Walnut Garlic",
                "Gijangbap",
                "Golbaengi Fire Noodle Salad",
                "Grilled Perilla Leaf Tofu",
                "Grilled Tofu",
                "Honey Bread",
                "Hwe Guksu",
                "Japchae Rice",
                "Jjolmyeon",
                "Joebap",
                "Kalguksu",
                "Kongbiji",
                "Kongtang",
                "Mak Noodle",
                "Mixed Grain Rice",
                "Mukbap",
                "Mukguk",
                "Mung Bean Rice",
                "Mung Bean Samgyetang",
                "Nose-Backed Noodles",
                "Oat Rice",
                "Patbings",
                "Pibab",
                "Pollack Tofu Stew",
                "Powder Made Of Mixed Grains",
                "Puffed Rice",
                "Ramen Rice",
                "Red Bean Jelly",
                "Red Bean Noodle Soup",
                "Rice Cake Dumpling Soup",
                "Rice Tteokbokki",
                "Rice With Grilled Pancake",
                "Shirutteok",
                "Small Walnut-Flavored Cake",
                "Spicy Cold Noodles",
                "Spinned Bean Paste Soup",
                "Steamed Buns",
                "Stir-Fried Rice Cake",
                "Stir-Fried Udon",
                "Tadpole Noodles",
                "Tofu And Soybean Paste",
                "Tofu Chagle",
                "Tofu Gangjeong",
                "Tofu Kimchi Egg Soup",
                "Tofu Kimchi",
                "Tofu Pancake",
                "Tofu Rice",
                "Tofu Spam Kimchi Hot Pot",
                "Tofu Spinach Salad",
                "Tray Jjajang",
                "Tray Membrane Noodles",
                "Udon",
                "Wanjatang",
                "Wheat Noodles",
                "Yakbap",
                "Yugwa",
                "Yulmu Bap",
        };
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, grainsitems);
        ListView listView = (ListView) findViewById(R.id.grainslist);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(
                new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int i, long id) {
                        String grainsitems = String.valueOf(parent.getItemAtPosition(i));
                        Toast.makeText(TertiaryActivity_ingredients_grains.this, grainsitems, Toast.LENGTH_SHORT);
                    }
                }
        );
    }
}