package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Toast;

/** List of recipes which fishes are the main ingredients of the recipe */
public class TertiaryActivity_ingredients_fish extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tertiary_ingredients_fish);

        String[] fishitems = {"Oyster Porridge",
                "Abalone Porridge",
                "Seafood Noodle",
                "Cold Raw Fish Noodles",
                "Fish Dumpling",
                "Sujebi",
                "Ae Stew",
                "Seaweed Soup",
                "Dried Pollack Soup",
                "Fish Roe Soup",
                "Clam Soup",
                "Chochi Soup",
                "Cod Soup",
                "Chueotang",
                "Ecological Stew",
                "Oyster Tofu Stew",
                "Salted Pollack Roe Stew",
                "Sea Bream Noodles",
                "Seafood Stew",
                "Octopus Stew",
                "Fresh Furnace",
                "Steamed Large Fish",
                "Squid Sundae",
                "Steamed Monkfish",
                "Tangpyeongchae",
                "Braised Hairtail Radish",
                "Braised Radish Mackerel",
                "Braised Fish",
                "Braised Early",
                "Abalone Plant",
                "Mussel Grass",
                "Stir-Fried Octopus",
                "Grilled Oysters",
                "Grilled Mackerel",
                "Grilled Dried Pollack",
                "Grilled Hairtail",
                "Grilled Early Seasoning",
                "Guljeon",
                "Pancake Shrimp Pancake",
                "Seafood Pajeon",
                "Raw Skate",
                "Raw Octopus",
                "Green Onion Bundles",
                "Salted Oysters With Hot Pepper",
                "Soy Sauce Marinated Crab",
                "Salted Squid",
                "Flatfish Sikhae",
                "Stir-Fried Octopus And Thin Noodles",
                "Braised Anchovies And White Beans",
                "Braised Dried Anchovies",
                "Braised Potato Fish Cake",
                "Braised Radish Kodari",
                "Dried Pollack Stick Rice Gangjeong",
                "Stir-Fried Garlic Dried Shrimp",
                "Stir-Fried Small Anchovy Nuts",
                "Stir-Fried Anchovy And Chili Paste",
                "Stir-Fried Squid Salad",
                "Grilled Braised Spice With Spicy Sauce",
                "Grilled Kodari Seasoning",
                "Seasoned Raw Oysters",
                "Seasoned Skate",
                "Seasoned Sea Snails",
                "Mussel Seaweed Soup",
                "Clear Soup With Cod",
                "Soybean Paste Soup With Ramie Clam",
                "Spicy Seafood Soup",
                "Fish Cake Stew",
                "Grilled Radish Rice",
                "Jellyfish Cold Salad",
                "Bulgogi Webfoot Octopus Stew",
                "Cold Salad With Seafood",
                "Seasoned Fish And Pork",
                "Stir-Fried Spinach Shrimp",
                "Salted Sea Squirt",
                "Braised Saury",
                "Seasoned Seasoned Seasoned Seasoned Seasoned With Vegetables",
                "Seasoned With Dried Pollack",
                "Seafood Egg Soup",
                "Steamed Tofu Shrimp",
                "Fresh Fish Soup",
                "Rice With Tuna Sashimi",
                "Pollack Egg Roll",
                "Grilled Samchigo Chili Sauce",
                "Braised Squid Soy Sauce",
                "Braised Mackerel Kimchi",
                "Seaweed Soup With New Egg Mussels",
                "Oyster Soup",
                "Samchi Cracker",
                "Seafood Soybean Paste Pot",
                "Steamed Kodari",
                "Stir-Fried Dried Shrimp",
                "Braised Bungeoppo",
                "Stir-Fried Squid Soy Sauce",
                "Braised Clams",
                "Seasoned Cockles",
                "Stir-Fried Red Pepper Paste With Dried Pollack",
                "Oyster Kimchi Soup And Rice",
                "Salted Pollack Roe Tofu Stew",
                "Dongtae Spicy Soup",
                "Braised Octopus Stew",
                "Sea Cucumber Nurungji Soup",
                "Seafood Salad",
                "Grilled Oyster Skewers",
                "Oyster Salad",
                "Seasoned Skate Sashimi",
                "Manila Clam Kalguksu",
                "Seasoned Webfoot Octopus Sashimi",
                "Grilled Clam Butter",
                "Spicy Rockfish Soup",
                "Seasoned Blue Crabs",
                "Fried Yellow Croake",
                "Grilled Webfoot Octopus Seasoning",
                "Blue Crab Stew",
                "Squid Spicy Soup",
                "Stir-Fried Squid",
                "Mungge Bibimbap",
                "Abalone Vinegar Sashimi",
                "Eel Nutrition Rice",
                "Eel Chives Soup",
                "Octopus Yeonpo Soup",
                "Mussel Clear Soup",
                "Seasoned With Julienne",
                "Fried Shrimp",
                "Grilled Shrimp Skewers",
                "Grilled Gizzard",
                "Raw Onion Octopus",
                "Steamed Kimchi With Seasoned Mackerel",
                "A Rice Topped With Tonkatsu",
                "Kkomak Bibimbap",
                "Squid Radish Soup",
                "Mussel Fish Cake Soup",
                "Squid Spicy Seafood Noodles",
                "Stir-Fried Seafood Udon",
                "Seafood Pasta",
                "Smoked Salmon",
                "Squid Minari Ganghoe",
                "Seaweed Oyster Soup",
                "Grilled Abalone Butter",
                "Grilled Eel",
                "Salmon Steak",
                "Cramey Fried Tofu Rice Balls",
                "Green Algae Guljeon",
                "Frozen Pollack Pancake",
                "Grilled Mackerel Soy Sauce",
                "Grilled Eel Yangyeom",
                "Seasoned Octopus Candle",
                "Braised Dried Mussels",
                "Bang-A-Po-Y",
                "Seasoned Dried Pollack",
                "Abalone Dolsotbap",
                "Abalone Earthen Pot",
                "Abalone Kimchi",
                "Agwi-Tang",
                "Albap",
                "Blue Crab Soup",
                "Braised Abalone",
                "Braised Cutlassfish",
                "Braised Mackerel And Kimchi",
                "Braised Mackerel",
                "Braised Pollack",
                "Braised Skate",
                "Braised Tuna Potatoes",
                "Broccoli Tuna Warfare",
                "Bulnakjeongol",
                "Cabbage Tuna Over Rice",
                "Clam Kalguksu",
                "Cockle-Minarimuchim",
                "Cold Jellyfish Salad",
                "Cold Noodles With Pollack",
                "Cold Raw Fish Soup",
                "Dongtaejeon",
                "Doribangbangi",
                "Dried Pollack Hangover Soup",
                "Dried Pollack Salad",
                "Dried Pollack",
                "Eojuk",
                "Fish Cake Kimchi Jeongol",
                "Fish Cake Pancake",
                "Fish Cake Soup",
                "Fried Oysters",
                "Fried Squid",
                "Galchi Pumpkin Soup",
                "Galnaktang",
                "Gazamijorim",
                "Ge Gukji",
                "Golbaengi Fire Noodle Salad",
                "Grilled Herring",
                "Grilled Shrimp",
                "Guamegi Raw Fish Salad",
                "Gulguk",
                "Hot Pepper Paste Tuna Fried Rice",
                "Hwe Guksu",
                "Jjambbong",
                "Jjangdung Fish Soup",
                "Joggi-Guk",
                "Marsh Snail Soup",
                "Mussel Herb",
                "Mussel Soup",
                "Nakjigui",
                "Octopus Lotus Pot Stew",
                "Odengguk",
                "Oyster Rice Soup",
                "Oyster Stew",
                "Paprika Tuna Warfare",
                "Pollack Soup",
                "Pollack Tofu Stew",
                "Rice Topped With Octopus",
                "Rice With Squid",
                "Roasted Abalone",
                "Salmon Soy Sauce Braised",
                "Salted Oysters",
                "Samhap",
                "Sea Snails Salad",
                "Sea Urchin Seaweed Soup",
                "Seafood Nurungji Soup",
                "Seasoned Cockle",
                "Seasoned Crab Radish",
                "Seasoned Oyster",
                "Shellfish Soup",
                "Shrimp Soft Tofu Egg Soup",
                "Shrimp Soup",
                "Shrimp Sweet Noodles Rice With Rice",
                "Spiced Squid",
                "Spicy Blue Crab Sauce Marinated Spicy Sauce",
                "Spicy Fish Stew",
                "Squid Bulgogi",
                "Squid Duruchigi",
                "Squid Kimchi",
                "Steamed Dried Corvina",
                "Steamed Sea Squirt Bibimbap",
                "Steamed Snow Crab",
                "Steamed Stingray",
                "Stew Made With Frozen Pollack",
                "Stir-Fried Anchovies",
                "Stir-Fried Pumpkin Tuna",
                "Stir-Fried Shrimp Cheonggyeongchae",
                "Stir-Fried Shrimp",
                "Stir-Fried Zucchini Shrimp",
                "Tray Jjajang",
                "Tuna Bibimbap",
                "Tuna Kimchi Porridge",
                "Webfoot Octopus Lotus Pot Soup",
                "Webfoot Octopus Salad",
                "Yeonpo-Tang",
                "Yushan Seul",
        };
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, fishitems);
        ListView listView = (ListView) findViewById(R.id.fishlist);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(
                new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int i, long id) {
                        String fishitems = String.valueOf(parent.getItemAtPosition(i));
                        Toast.makeText(TertiaryActivity_ingredients_fish.this, fishitems, Toast.LENGTH_SHORT);
                    }
                }
        );
    }
}