package com.example.korean_food;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import android.widget.Toast;

/** List of recipes which vegetables are the main ingredients of the recipe */
public class TertiaryActivity_ingredients_vegetables extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tertiary_ingredients_vegetables);

        String[] vegetablesitems = {"Bibimbap",
                "Rice Roll",
                "Grilled Porridge",
                "Fish Tray",
                "Bibim Noodles",
                "Spicy Buckwheat Noodles",
                "Sublime Dumpling",
                "Seaweed Soup",
                "Sea Mustard Soup",
                "Radish Paste Soup",
                "Bean Sprout Soup",
                "Toran Stew",
                "Hot Spicy Meat Stew",
                "Naengi Soup",
                "Cabbage Soup",
                "Spinach Soup",
                "Aukguk",
                "Cold Cucumber Soup",
                "Umu Cold Soup",
                "Soy Bean Paste Stew",
                "Wild Chive Soy Bean Paste Stew",
                "Bean Paste Stew",
                "Raw Beef Stew",
                "Ecological Stew",
                "Salted Zucchini Soup Stew",
                "Kimchi Stew",
                "Mushroom Stew",
                "Sea Bream Noodles",
                "Seafood Stew",
                "Octopus Stew",
                "Tofu Stew",
                "Fresh Furnace",
                "Pumpkin Sone",
                "Cucumber",
                "Branched",
                "Eggplant Greens",
                "Gujeolpan",
                "Bracken Greens",
                "Canine Leaf Vegetables",
                "Cold Greens",
                "Balloon Flower",
                "Water Parsley",
                "Radish Greens",
                "Knee Greens",
                "Mewi Greens",
                "Pogo Mushroom Vegetables",
                "Mungbean Sprouts",
                "Spinach Greens",
                "Dried Radish Leaves",
                "Zucchini Greens",
                "Chwinamul",
                "Bean Sprouts",
                "Japchae",
                "Bamboo Shoots",
                "Tangpyeongchae",
                "Salted Salad",
                "Deodeok Saengchae",
                "Spicy Spring Salted Vegetables",
                "Raw Radish Salad",
                "Raw Cucumbers",
                "Chamul Raw Salted Salad",
                "Seasoned Seaweed",
                "Mustard Vegetables",
                "Seasoned Acorns",
                "Seasoned Buckwheat Cake",
                "Braised Lotus Root",
                "Potato Pancake",
                "Sesame Leaf Pancake",
                "Red Pepper Pancake",
                "Zucchini Pancake",
                "Before Lotus Root",
                "Mushroom Pancake",
                "Bindaetteok",
                "Jangtteok",
                "Sub-San-Jeok",
                "Songi-San-Jeok",
                "Raw Dureup",
                "Green Onion Bundles",
                "Water Parsley And Beef Ties",
                "Kim Bu-Gak",
                "Knot Rice Bowl",
                "Pickled Red Pepper",
                "Pickled Sesame Leaves",
                "Pickled Garlic",
                "Pickled Garlic Pickles",
                "Pickled Radish",
                "Cucumber And Beef",
                "Cabbage Kimchi",
                "Bossam Kimchi",
                "White Kimchi",
                "Cubed Radish Kimchi",
                "Chonggak Kimchi",
                "Nabak Kimchi",
                "Dongchimi",
                "Pomegranate Kimchi",
                "Fresh Kimchi",
                "Long Kimchi",
                "Godeulgi Kimchi",
                "Young Radish Kimchi",
                "Cucumber Gourd",
                "Green Onion Kimchi",
                "Pumpkin Rice Cake",
                "Balloon Flower Garden And",
                "Lotus Root Pavilion",
                "Ginger Eggs",
                "Bamcho",
                "Jujube Grass",
                "Ginseng Tea",
                "Ginger Tea",
                "Potato Chili Paste Stew",
                "Beef Pyeony Salad",
                "Chives Pancake",
                "Acorn Pancake",
                "Perilla Soup",
                "Braised Dried Anchovies",
                "Braised Burdock Pork Roll",
                "Braised Konjac",
                "Braised Potato Fish Cake",
                "Steamed Perilla Leaves",
                "Stir-Fried Garlic Dried Shrimp",
                "Stir-Fried Burdock Salad",
                "Stir-Fried Seaweed Stem",
                "Dry Green Algae Dish",
                "Squid And Pork Belly Bulgogi",
                "Grilled Eggplant Seasoning",
                "Leaf Greens",
                "Dried Eggplant Greens",
                "Seasoned With Water Blue",
                "Seasoned With Garlic Bell Pepper Paste",
                "Seasoned With Green Pepper Paste",
                "Pickled Soy Radish",
                "Pickled Mushrooms",
                "Pickled Green Pepper Soy Sauce",
                "Pickled Pollack",
                "Pickled Cucumbers",
                "Pickled Bean Leaves With Soybean Paste",
                "Pickled Kimchi",
                "Pickled Onions",
                "Cucumber Pickles",
                "Cabbage Pickles",
                "Paprika Pickles",
                "Seasoned Cabbage",
                "Chives Kimchi",
                "Green Pepper Kimchi",
                "Cucumber Kimchi",
                "Instant Water Kimchi",
                "Cheongpo Mukjeon",
                "Mussel Seaweed Soup",
                "Burdock Perilla Soup",
                "Soybean Paste Soup With Vegetables",
                "Thick Soybean Paste Soup",
                "Spicy Seafood Soup",
                "Seaweed Cucumber Cold Soup",
                "Rice With Seasoned Thistle",
                "Seaweed Abalone Porridge",
                "Fruit Salad",
                "Lotus Root Salad",
                "Bulgogi Cold Salad",
                "Jellyfish Cold Salad",
                "Seasoned Green Onion Salad With Meat",
                "Seaweed Vinegar Sashimi",
                "Ginger Dry Fruit",
                "Salted Greens",
                "Soybean Sauce",
                "Stir-Fried Laver",
                "Seasoned With Chubby Balloon Flower",
                "Stir-Fried Spinach Shrimp",
                "Red Pepper Kimchi",
                "Thermal Movie Beam Surface",
                "Braised Quarigo Chives",
                "Seasoned Cucumbers",
                "Pickled Deodeok",
                "Braised Kelp",
                "Stir-Fried Eggplant",
                "Seaweed Soup With New Egg Mussels",
                "Green Laver Pancake",
                "Seasoned Green Laver",
                "Beef Vegetable Roll",
                "Pork Back-Bone Stew",
                "Sweet Potato Sweet Pumpkin Salad",
                "Windproof Vegetable Seasoning",
                "Chamulmuul Radish",
                "Korean Melon Kkakdugi",
                "Cold Buckwheat Buckwheat Noodles",
                "Seasoned Coriander",
                "Strong Tofu Red Pepper Paste",
                "Burdock Pickles",
                "Chwinamul Soy Bean Paste Soup",
                "Seasoned Cheongpo Muk",
                "Braised Sweet Pumpkin",
                "Assorted Ssambap",
                "Burdock Japchae",
                "Mushroom Soft Tofu Perilla Soup",
                "Mushroom Mustard Cold Salad",
                "Sesame Leaf Stir-Fry",
                "Stir-Fried Onions",
                "Enoki Mushroom Vegetable Pancake",
                "Lettuce Fresh Kimchi",
                "Seasoned Seaweed With Vinegar",
                "Braised Radish",
                "Broccoli Tofu Salad",
                "Seasoned Wild Vegetables",
                "Seasoned Salad",
                "Seasoned Onion Cucumbers",
                "Stir-Fried Perilla Sprouts",
                "Braised Burdock",
                "Oyster Kimchi Soup And Rice",
                "Dongtae Spicy Soup",
                "Wheat Wrap",
                "Seafood Salad",
                "Oyster Salad",
                "Seasoned With Soothing",
                "Grilled Burdock Beef",
                "Spicy Rockfish Soup",
                "The Durbbakan Wrap",
                "Stir-Fried Bamboo Shoots",
                "Chwinamul Doenjang Salad",
                "Steamed Sea Squirt Bean Sprouts",
                "Chives Semi Kimchi",
                "Young Radish Greens",
                "Strong Doenjang Yeol Movie Bibimbap",
                "Yeolmu Kimchi Bibim Noodle",
                "Eel Chives Soup",
                "Toran Soup",
                "Toenmi Soy Bean Paste Soup",
                "Shiitake Beef Brisket Doenjang Stew",
                "Sweet And Sour Mushrooms",
                "Steamed Sweet Pumpkin",
                "Steamed Kimchi With Seasoned Mackerel",
                "Radish Bean Sprout Soup",
                "Kimchi Fried Rice",
                "Yeolmu Bibimbap",
                "Spicy Sausage Stew",
                "Pork Kimchi Stew",
                "Beef Radish Soup",
                "Squid Radish Soup",
                "Noodles For The Feast",
                "Bibimdangmyeon",
                "Mille-Feuille-Nabe",
                "Steamed Pork Belly Kimchi Roll",
                "Pan-Fried Pork Belly Host Food",
                "Squid Minari Ganghoe",
                "Sweet Pumpkin Porridge",
                "Sweet Potato Mattang",
                "Seasoned Chives And Cucumbers",
                "Kimjaban",
                "Grilled Tofu Salad",
                "Green Algae Guljeon",
                "Seasoned Buckwheat Muk Kimchi",
                "Chicken Breast Mustard Salad",
                "Stir Fried Beef Bok Chung Oyster",
                "Braised Beef Wan",
                "Braised Quarigo Chili Eggs",
                "Braised King Oyster Mushroom",
                "Splashing Kelp",
                "Abalone Kimchi",
                "Ah Wook Guk",
                "Banquet Noodles",
                "Bean Leaf Kimchi",
                "Bean Paste Cabbage Soup",
                "Bean Sprout Hangover Soup",
                "Bean Sprout Konjac Bibimmyeon",
                "Bean Sprout Mushroom Stew",
                "Beef Cabbage Soup",
                "Bibimguks",
                "Bom-Dong Odejeoljeol",
                "Bossam",
                "Braised Back Rib Kimchi",
                "Braised Chestnut",
                "Braised Garlic Almonds",
                "Braised Mackerel And Kimchi",
                "Braised Old Kimchi",
                "Braised Pork Garlic",
                "Braised Red Pepper",
                "Braised Tuna Potatoes",
                "Broccoli Tuna Warfare",
                "Bungnamul",
                "Burdock Kimchi",
                "Cabbage Tuna Over Rice",
                "Carrot Rice",
                "Carrot Seasoned With Grilled Radish",
                "Chinese Cabbage Leaf",
                "Chinese Cabbage Soup",
                "Chives Bacon Mallet",
                "Chives Japchae",
                "Chungmu Gimbap",
                "Chupotang",
                "Cockle-Minarimuchim",
                "Cold Bean Sprout Salad",
                "Cold Jellyfish Salad",
                "Cold Soup",
                "Cucumber Pickle",
                "Cucumber Salad",
                "Deep-Fried Sweet Pumpkin",
                "Deodeok Jangaji",
                "Deodeok Kimchi",
                "Doraji Saengchae",
                "Dorajigwa",
                "Dorajimuchim",
                "Dried Pollack Salad",
                "Dried Radish Greens",
                "Dried Radish Kimchi",
                "Dried Radish Salad",
                "Dried Radish",
                "Dried Soybean Paste Seasoned With Dried Radish Leaves",
                "Dumpling Hot Pot",
                "Dumpling",
                "Egg Dumpling",
                "Eggplant Rice",
                "Eggplant Sprouts",
                "Eggplant Tangsu",
                "Eolchutang",
                "Fish Cake Kimchi Jeongol",
                "Fried Cheese Potato",
                "Fried Eggplant",
                "Fried Onion",
                "Fried Rice",
                "Fried Sweet Potatoes",
                "Fried Vegetables",
                "Galchi Pumpkin Soup",
                "Gamjazugoroke",
                "Garlic Pickle",
                "Ginger Process",
                "Ginseng Process",
                "Godeulpaegi Kimchi",
                "Gondre Rice",
                "Gondrenamul",
                "Green Pepper Salad",
                "Grilled Deodeok",
                "Grilled Perilla Leaf Tofu",
                "Grilled Saesongi Mushroom Soy Sauce",
                "Grilled Saesongi",
                "Hangover Soup",
                "Honey Butter Sweet Potato",
                "Jjambbong",
                "Kim Moo-Chim",
                "Kimchi Pancake",
                "Kimchi Soup",
                "Kimchi Sujebi",
                "Kkakdugi",
                "Ko Ji-Guk",
                "Leek Kimchi",
                "Leek Pancake",
                "Lettuce Leaf Salad",
                "Lotus Leaf Rice",
                "Lotus Root Stewing",
                "Mixed Kimchi",
                "Mugwort Rice Cake",
                "Mushroom Hot Pot",
                "Mushroom Jangjorim",
                "Mushroom Perilla Soup",
                "Oiseon",
                "Oisobak",
                "Onion Egg Rice",
                "Onion Kimchi",
                "Onion Pickle",
                "Owing Japchae",
                "Palbochae",
                "Paprika Beef Horse",
                "Paprika Tuna Warfare",
                "Pearl Bibimbap",
                "Perilla Leaf Jeon",
                "Perilla Leaf Kimchi",
                "Perilla Leaf Pickle",
                "Perilla Taro Soup",
                "Pickled Garlic Leaves",
                "Pickled Onion",
                "Pork And Hot Pepper Paste Stew",
                "Potato Ongshimi",
                "Potato Rice",
                "Potato Songpyeon",
                "Pumpkin Beombeok",
                "Pumpkin Pancake",
                "Pumpkin Soup",
                "Pyeongyang Hot Pot",
                "Radish Ssammari",
                "Red Pepper Paste Stew",
                "Rice Ball",
                "Rice Burger",
                "Rice With Enoki Mushroom",
                "Sanchae Bibimbap",
                "Sancho Pickled Vegetables",
                "Sea Snails Salad",
                "Sea Urchin Seaweed Soup",
                "Seasoned Bean Sprouts",
                "Seasoned Bracken",
                "Seasoned Cucumber",
                "Seasoned Leek",
                "Seasoned Perilla Leaves",
                "Seasoned Radish",
                "Seasoned Spinach",
                "Seaweed Bibimbap",
                "Seaweed Cold Soup",
                "Shiitake Pancake",
                "Shin Sun Ro",
                "Spring Roll",
                "Sprout Bibimbap",
                "Squid Kimchi",
                "Ssambap",
                "Steamed Sausage Bean Sprouts",
                "Steamed Soybean Paste Perilla Leaves",
                "Stir-Fried Bean Sprouts And Eggs",
                "Stir-Fried Beef Cheonggyeongchae",
                "Stir-Fried Beef Cucumber",
                "Stir-Fried Chicken Breast Mushroom",
                "Stir-Fried Chicken Breast Perilla Leaves",
                "Stir-Fried Cucumber",
                "Stir-Fried Garlic Species",
                "Stir-Fried Potatoes",
                "Stir-Fried Pumpkin Tuna",
                "Stir-Fried Spam Potato",
                "Stir-Fried Zucchini Shrimp",
                "Sweet Potato Pancake",
                "Sweet Potato Soup",
                "Sweet Pumpkin Nutrition Rice",
                "Sweet Pumpkin Sikhye",
                "Tofu Kimchi Egg Soup",
                "Tofu Kimchi",
                "Tofu Spam Kimchi Hot Pot",
                "Tofu Spinach Salad",
                "Tuna Kimchi Porridge",
                "Turnip Kimchi",
                "Vegetable Porridge",
                "Water Parsley Kimchi",
                "Webfoot Octopus Salad",
                "Yeolmu Kimchi",
                "Yeon Geun Jeon",
                "Young Green Pepper Pancake",
                "Zucchini Egg Porridge",
        };
        ListAdapter adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, vegetablesitems);
        ListView listView = (ListView) findViewById(R.id.vegetableslist);
        listView.setAdapter(adapter);

        listView.setOnItemClickListener(
                new AdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int i, long id) {
                        String vegetablesitems = String.valueOf(parent.getItemAtPosition(i));
                        Toast.makeText(TertiaryActivity_ingredients_vegetables.this, vegetablesitems, Toast.LENGTH_SHORT);
                    }
                }
        );
    }
}